import assert from 'node:assert/strict';
import {chromium} from '@playwright/test';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const base=process.env.STUDIO_BASE_URL||'http://127.0.0.1:3000',out=process.env.STUDIO_VERIFICATION_DIR||'docs/evidence/t058/verification';await mkdir(out,{recursive:true});
const report={startedAt:new Date().toISOString(),kind:'actual-studio-browser-verification',base,checks:[],errors:[],badResponses:[],sourceUpload:null};
const browser=await chromium.launch({channel:'chrome',headless:true});let page;
const pass=(name,detail={})=>{report.checks.push({name,passed:true,...detail});console.log('PASS '+name);};
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
try{
 const context=await browser.newContext({viewport:{width:1672,height:941},deviceScaleFactor:1,acceptDownloads:true});page=await context.newPage();page.setDefaultTimeout(40000);
 page.on('pageerror',e=>report.errors.push(e.message));page.on('response',r=>{if(r.url().startsWith(base)&&r.status()>=400)report.badResponses.push({path:new URL(r.url()).pathname,status:r.status()});});
 await page.goto(base+'/',{waitUntil:'domcontentloaded',timeout:120000});await page.waitForURL(/\/studio/);
 await page.waitForFunction(()=>window.__CITY_DEBUG__?.controlConnected,{},{timeout:120000});await page.waitForTimeout(2000);
 assert.equal(await page.locator('canvas[data-studio-canvas]').count(),1);assert.equal(await page.getByTestId('selected-ulpin').textContent(),'11007500003527');
 await page.evaluate(()=>{window.__STUDIO_ORIGINAL_CANVAS=document.querySelector('canvas[data-studio-canvas]');});
 report.graphics=await page.locator('canvas[data-studio-canvas]').evaluate(c=>{const gl=c.getContext('webgl2'),e=gl.getExtension('WEBGL_debug_renderer_info');return {renderer:gl.getParameter(e.UNMASKED_RENDERER_WEBGL),version:gl.getParameter(gl.VERSION)};});
 pass('Plain product entry opens the copied Studio, with one persistent GPU canvas');
 const canvas=page.locator('.map-viewport canvas'),box=await canvas.boundingBox();assert(box);
 const before=await page.evaluate(()=>window.__CITY_DEBUG__);
 await page.mouse.move(box.x+box.width*.55,box.y+box.height*.35);await page.mouse.down();await page.waitForTimeout(700);await page.mouse.move(box.x+box.width*.6,box.y+box.height*.42,{steps:18});await page.mouse.up();await page.waitForTimeout(400);
 const moved=await page.evaluate(()=>window.__CITY_DEBUG__);assert(Math.hypot(...moved.target.map((v,i)=>v-before.target[i]))>.1);
 await page.mouse.down({button:'right'});await page.waitForTimeout(700);await page.mouse.move(box.x+box.width*.68,box.y+box.height*.40,{steps:18});await page.mouse.up({button:'right'});await page.waitForTimeout(300);
 const orbit=await page.evaluate(()=>window.__CITY_DEBUG__);assert(Math.abs(orbit.azimuth-moved.azimuth)>.001);await page.mouse.wheel(0,-150);await page.waitForTimeout(250);
 assert((await page.evaluate(()=>window.__CITY_DEBUG__.zoom))>orbit.zoom);pass('Held native pan, right-drag orbit and wheel zoom remain connected during UI updates');
 await page.getByRole('button',{name:'Fit block',exact:true}).click();await page.waitForTimeout(1800);
 const roof=await page.evaluate(()=>window.__CITY_PROJECT__('BLD-0413'));assert(roof);
 const pickBefore=await page.evaluate(()=>window.__CITY_DEBUG__);
 await page.locator('.property-list .property-row').nth(1).click();assert.notEqual(await page.getByTestId('selected-ulpin').textContent(),'11007500003527');
 await page.waitForTimeout(350);
 const currentBox=await canvas.boundingBox(),currentRoof=await page.evaluate(()=>window.__CITY_PROJECT__('BLD-0413'));
 report.pick={boxBefore:box,boxNow:currentBox,projectedBefore:roof,projectedNow:currentRoof,cameraBefore:pickBefore,cameraAfter:await page.evaluate(()=>window.__CITY_DEBUG__)};
 // __CITY_PROJECT__ reports absolute CSS viewport coordinates, like a real pointer.
 await page.mouse.click(currentRoof.x,currentRoof.y);await page.waitForFunction(()=>document.querySelector('[data-testid="selected-ulpin"]')?.textContent==='11007500003527');
 pass('Actual canvas raycasting selects the prepared property, not a list-only simulation');
 await page.getByRole('button',{name:'Utilities',exact:true}).click();assert.match(page.url(),/tab=utilities/);await page.goBack();await page.getByRole('button',{name:'Overview',exact:true}).waitFor();
 await page.getByRole('button',{name:'2D',exact:true}).click();await page.waitForTimeout(1600);assert((await page.evaluate(()=>window.__CITY_DEBUG__.polar))<.003);assert.match(page.url(),/mode=2d/);
 await page.getByRole('button',{name:'3D',exact:true}).click();await page.waitForTimeout(1600);
 await page.getByRole('button',{name:'Underground',exact:true}).click();await page.getByRole('button',{name:'Underground',exact:true}).click();
 await page.getByRole('button',{name:'Labels',exact:true}).click();await page.getByRole('button',{name:'Labels',exact:true}).click();
 pass('Inspector URL history, orthographic mode, underground and label controls operate on the same scene');
 const cameraBeforeRegister=await page.evaluate(()=>window.__CITY_DEBUG__);
 await page.getByRole('button',{name:'Full register',exact:true}).click();await page.waitForSelector('.register-overview');await page.waitForTimeout(700);
 assert.equal(await page.locator('canvas[data-studio-canvas]').count(),1);assert(await page.evaluate(()=>document.querySelector('canvas[data-studio-canvas]')===window.__STUDIO_ORIGINAL_CANVAS));
 await page.locator('[data-unit-id="BLD-0413/F1/U1"]').click();await page.getByRole('button',{name:'Inspect record',exact:true}).click();assert.match(page.url(),/doc=lease/);assert.match(page.url(),/unit=BLD-0413%2FF1%2FU1/);
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'PDF',exact:true}).click();const download=await downloadPromise;const file=out+'/'+download.suggestedFilename();await download.saveAs(file);
 const manifest=await (await context.request.get(base+'/api/v1/studio/sources/manifest.json')).json();const specimen=manifest.documents.find(d=>d.id==='lease-BLD-0413-F1-U1');assert(specimen);assert.equal(sha(await readFile(file)),specimen.sha256);
 pass('Register reuses the canvas and downloads the exact prepared unit PDF with matching SHA-256',{document:specimen.id,sha256:specimen.sha256});
 const exactDocumentUrl=page.url();
 await page.getByRole('button',{name:'Back to map',exact:false}).click();await page.waitForSelector('.map-viewport canvas');await page.waitForTimeout(400);
 const restoredCamera=await page.evaluate(()=>window.__CITY_DEBUG__);
 assert(Math.hypot(...restoredCamera.target.map((v,i)=>v-cameraBeforeRegister.target[i]))<.2);
 assert(Math.abs(restoredCamera.zoom-cameraBeforeRegister.zoom)<.02);
 assert(await page.evaluate(()=>document.querySelector('canvas[data-studio-canvas]')===window.__STUDIO_ORIGINAL_CANVAS));
 pass('Returning from the register preserves the actual map camera and GPU canvas');
 await page.goto(exactDocumentUrl,{waitUntil:'domcontentloaded'});await page.waitForSelector('.rec-document');
 await page.reload();await page.waitForSelector('.rec-document',{timeout:120000});assert.equal(await page.getByLabel('Unit and occupant',{exact:true}).inputValue(),'BLD-0413/F1/U1');
 await page.getByRole('button',{name:'Back to map',exact:false}).click();await page.waitForSelector('.map-viewport canvas');await page.waitForTimeout(1500);
 // Reload intentionally allocated a new renderer; mark this lease for subsequent transitions.
 await page.evaluate(()=>{window.__STUDIO_ORIGINAL_CANVAS=document.querySelector('canvas[data-studio-canvas]');});
 pass('Property, floor, unit and document deep links survive a full reload');
 await page.getByRole('button',{name:'Open workspace',exact:true}).click();await page.waitForSelector('.studio-plan-workspace');await page.waitForTimeout(800);
 assert.equal(await page.locator('canvas[data-studio-canvas]').count(),1);assert(await page.evaluate(()=>document.querySelector('canvas[data-studio-canvas]')===window.__STUDIO_ORIGINAL_CANVAS));
 await page.getByRole('button',{name:'Distance',exact:true}).click();
 const positions=await page.locator('.spw-plan-stage>div:first-child>svg').evaluate(svg=>{const matrix=svg.getScreenCTM(),s=298/18,left=(600-16*s)/2;return [[-4,1],[-1,5]].map(([x,z])=>{const p=new DOMPoint(left+(x+8)*s,64+(z+9)*s).matrixTransform(matrix);return {x:p.x,y:p.y};});});
 for(const p of positions)await page.mouse.click(p.x,p.y);
 // Pointer events are quantized to browser pixels; the independent numeric unit
 // test is exact. At this plan scale, allow at most three centimetres for clicks.
 const clickedDistance=parseFloat(await page.locator('[data-workspace-measurement]').textContent());assert(Math.abs(clickedDistance-5)<=.03);
 await page.getByRole('button',{name:'Calibrate',exact:true}).click();await page.getByLabel('Draft scale factor').fill('2');const scaledDistance=parseFloat(await page.locator('[data-workspace-measurement]').textContent());assert(Math.abs(scaledDistance-clickedDistance*2)<=.02);await page.getByRole('button',{name:'Use source scale'}).click();
 await page.getByRole('button',{name:'Save draft',exact:true}).first().click();await page.getByText(/Local draft revision 1 saved/).waitFor();
 const localDraft=await page.evaluate(()=>JSON.parse(localStorage.getItem('ulpin:studio-local-draft:v2:BLD-0413:F1')));assert.equal(localDraft.sourceHash,manifest.datasetSha256);assert.equal(localDraft.points.length,2);assert.equal(localDraft.revision,1);
 await page.getByRole('button',{name:'Queue for review'}).click();await page.getByText(/Added to the local review queue/).waitFor();
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('ulpin:studio-local-draft:v2:BLD-0413:F1')).status),'ready_for_review');
 await page.getByRole('button',{name:'Compare',exact:true}).click();assert.equal(await page.locator('.spw-comparison').count(),1);await page.getByRole('button',{name:'Compare',exact:true}).click();
 await page.getByRole('button',{name:'Next floor',exact:true}).click();assert.match(page.url(),/floor=2/);assert.equal(await page.locator('[data-workspace-measurement]').count(),0);
 pass('Workspace measures source coordinates, scales only the draft, persists a revision and clears measurements across floors',{expectedDistanceMetres:5,pointerMeasurementMetres:clickedDistance,pointerToleranceMetres:.03,localReviewOnly:true});
 await page.getByRole('button',{name:'Back to map',exact:true}).click();await page.waitForSelector('.map-viewport canvas');assert(await page.evaluate(()=>document.querySelector('canvas[data-studio-canvas]')===window.__STUDIO_ORIGINAL_CANVAS));
 await page.getByRole('button',{name:'Import',exact:true}).click();await page.getByRole('heading',{name:'Import & prepared data'}).waitFor();
 await page.getByRole('button',{name:'Prepared demo',exact:true}).click();await page.getByText(String(manifest.counts.documents),{exact:true}).waitFor();await page.screenshot({path:out+'/prepared-sources.png'});
 await page.getByRole('button',{name:'Upload original',exact:true}).click();
 if(process.env.STUDIO_TEST_UPLOAD==='1'){
  await page.getByLabel('Destination workspace').selectOption('');await page.getByLabel('New workspace name').fill('Studio T058 verification — synthetic source review');
  await page.getByRole('button',{name:'Use prepared ground-floor plan',exact:true}).click();
  const received=page.waitForResponse(r=>r.request().method()==='POST'&&/\/cases\/[^/]+\/sources$/.test(new URL(r.url()).pathname));
  await page.locator('.sti-body footer').getByRole('button',{name:'Upload original',exact:true}).click();
  const response=await received;assert.equal(response.status(),201);const source=await response.json();await page.getByRole('heading',{name:'Original source received'}).waitFor();
  const doc=manifest.documents.find(d=>d.id==='plan-BLD-0413-F0');assert.equal(source.sha256,doc.sha256);assert.equal(Number(source.bytes),doc.bytes);
  const original=await context.request.get(base+`/api/v1/sources/${source.id}/file`);assert.equal(original.status(),200);assert.equal(sha(await original.body()),doc.sha256);
  report.sourceUpload={sourceId:source.id,caseId:source.caseId,sha256:source.sha256,bytes:source.bytes,status:source.status,scope:'New synthetic verification workspace only'};
  await page.screenshot({path:out+'/real-source-receipt.png'});
  pass('Studio upload writes and downloads an actual byte-identical original through the existing backend',{sourceId:source.id,status:source.status});
 }else pass('Prepared source browser verified; mutating upload deliberately disabled in this run');
 await page.getByRole('button',{name:'Close import',exact:true}).click();
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(1000);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.getByRole('button',{name:'Expand property details',exact:true}).click();await page.getByRole('button',{name:'Open workspace',exact:true}).waitFor({state:'visible'});await page.screenshot({path:out+'/mobile-inspector.png'});
 await page.getByRole('button',{name:'Open workspace',exact:true}).click();await page.waitForSelector('.studio-plan-workspace');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:out+'/mobile-workspace.png'});
 await page.getByRole('button',{name:'Back to map',exact:true}).click();
 pass('Mobile property and workspace routes remain usable without horizontal page overflow or a second canvas');
 await page.goto(base+'/studio/register/not-a-building');await page.getByRole('heading',{name:'That record is unavailable'}).waitFor();assert.equal(await page.locator('.map-viewport').count(),0);
 pass('Unknown routed records are unavailable, not silently replaced with the showcase property');
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.badResponses,[]);report.result='PASS';
}catch(error){report.result='FAIL';report.error=error.stack||String(error);console.error(report.error);if(page)await page.screenshot({path:out+'/failure.png'}).catch(()=>{});process.exitCode=1;}finally{await browser.close();report.finishedAt=new Date().toISOString();await writeFile(out+'/results.json',JSON.stringify(report,null,2)+'\n');}
