'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Download,Scissors} from 'lucide-react';
import {prismSection,sectionBounds,type SectionBody,type SectionAxis} from './data/section';
import './section.css';

export default function SectionView({bodies,selectedId,onSelect}:{bodies:SectionBody[];selectedId?:string|null;onSelect?:(id:string)=>void}){
 const refs=[...new Set(bodies.map(b=>b.reference))];
 const [reference,setReference]=useState(refs[0]??''),[axis,setAxis]=useState<SectionAxis>('east-west'),[fraction,setFraction]=useState(.5);
 const qualified=bodies.filter(b=>b.reference===reference),bounds=sectionBounds(qualified),svg=useRef<SVGSVGElement>(null);
 useEffect(()=>{if(!refs.includes(reference))setReference(refs[0]??'');},[refs.join('|'),reference]);
 const cross=axis==='east-west'?1:0,along=1-cross;
 const position=bounds?bounds[cross]+(bounds[cross+2]-bounds[cross])*fraction:0;
 const spans=useMemo(()=>qualified.flatMap(b=>prismSection(b,axis,position)),[qualified,axis,position]);
 if(!bounds)return <div className="section-unavailable"><Scissors size={27}/><h3>Section geometry not supplied</h3><p>A section needs source-local boundaries and explicit lower/upper elevations in the same vertical reference. Missing interior volumes are not inferred.</p></div>;
 const width=Math.max(.1,bounds[along+2]-bounds[along]),height=Math.max(.1,bounds[5]-bounds[4]),scale=Math.min(650/width,350/height),x0=85,y0=405;
 const X=(x:number)=>x0+(x-bounds[along])*scale,Y=(z:number)=>y0-(z-bounds[4])*scale;
 const exportView=()=>{if(!svg.current)return;const source=new XMLSerializer().serializeToString(svg.current),url=URL.createObjectURL(new Blob([source],{type:'image/svg+xml'})),a=document.createElement('a');a.href=url;a.download='source-derived-building-section.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section className="source-section" aria-label="Building section"><header><strong><Scissors size={16}/>Source-derived section</strong><div><select aria-label="Section orientation" value={axis} onChange={e=>setAxis(e.target.value as SectionAxis)}><option value="east-west">East–west section</option><option value="north-south">North–south section</option></select>{refs.length>1&&<select aria-label="Section vertical reference" value={reference} onChange={e=>setReference(e.target.value)}>{refs.map(r=><option key={r}>{r}</option>)}</select>}<button onClick={exportView}><Download size={14}/>SVG</button></div></header>
  <svg ref={svg} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 820 470" role="img" aria-label={`${axis} section at ${position.toFixed(2)} metres in ${reference}`}><rect width="820" height="470" fill="#f8faf7"/>{Array.from({length:6},(_,i)=>bounds[4]+(bounds[5]-bounds[4])*i/5).map(z=><g key={z}><line x1={65} x2={760} y1={Y(z)} y2={Y(z)} stroke="#dfe8da"/><text x={55} y={Y(z)+4} textAnchor="end" fill="#7a9071" fontSize="11" fontFamily="sans-serif">{z.toFixed(1)} m</text></g>)}{spans.map((s,i)=><g key={`${s.id}:${i}`} role="button" tabIndex={0} aria-label={`${s.label}, ${s.lower} to ${s.upper} metres`} onClick={()=>onSelect?.(s.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect?.(s.id);}}}><rect x={X(s.start)} y={Y(s.upper)} width={(s.end-s.start)*scale} height={(s.upper-s.lower)*scale} rx="1" fill={s.id===selectedId?'#d4b669':'#a3c7b0'} fillOpacity=".7" stroke={s.id===selectedId?'#997136':'#548c6b'} strokeWidth={s.id===selectedId?2:1.1}/>{(s.end-s.start)*scale>65&&<text x={(X(s.start)+X(s.end))/2} y={(Y(s.lower)+Y(s.upper))/2+4} textAnchor="middle" fontSize="11" fill="#416b4e" fontFamily="sans-serif">{s.label.length>24?s.label.slice(0,22)+'…':s.label}</text>}<title>{s.label} · {s.lower}–{s.upper} m · width {(s.end-s.start).toFixed(2)} m</title></g>)}<line x1={X(bounds[along])} x2={X(bounds[along+2])} y1={421} y2={421} stroke="#6a8460"/><text x={X(bounds[along])} y={440} fill="#6a8460" fontSize="11" fontFamily="sans-serif">{bounds[along].toFixed(2)} m</text><text x={X(bounds[along+2])} y={440} textAnchor="end" fill="#6a8460" fontSize="11" fontFamily="sans-serif">{bounds[along+2].toFixed(2)} m</text><text x={760} y={24} textAnchor="end" fill="#718466" fontSize="11" fontFamily="sans-serif">{axis==='east-west'?'Source Y':'Source X'} {position.toFixed(2)} m</text>{!spans.length&&<text x={410} y={235} textAnchor="middle" fill="#829177" fontSize="15" fontFamily="sans-serif">This cut does not intersect a retained volume.</text>}</svg>
  <footer><label>Cut position <input type="range" aria-label="Section cut position" min="0.001" max="0.999" step=".001" value={fraction} onChange={e=>setFraction(Number(e.target.value))}/><b>{position.toFixed(2)} m</b></label><p>Vertical reference: <strong>{reference}</strong>. No floor separation or vertical exaggeration is included.</p></footer>
 </section>;
}
