// Builds @ulpin/design-system from the artifact sources in ../source:
//   source/tokens.json   -> dist/tokens.css (compiled the way the Design System artifact compiles it)
//   source/icons/*.svg   -> src/icons.data.ts (Phosphor Regular path data)
//   source/bundle.css    -> dist/bundle.css (verbatim)
//   src/index.ts         -> dist/index.js (ESM, react external) + dist/*.d.ts
import { build } from 'esbuild';
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync, copyFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = (p) => join(root, 'source', p);
const dist = join(root, 'dist');

rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });

// Icons
const iconDir = src('icons');
const icons = {};
for (const f of readdirSync(iconDir).filter((f) => f.endsWith('.svg')).sort()) {
  const svg = readFileSync(join(iconDir, f), 'utf8');
  icons[f.slice(0, -4)] = [...svg.matchAll(/<path d="([^"]*)"/g)].map((m) => m[1]);
}
writeFileSync(
  join(root, 'src/icons.data.ts'),
  '// Generated by scripts/build.mjs from source/icons (Phosphor Regular, MIT). Do not edit.\n' +
    `export const ICON_PATHS = ${JSON.stringify(icons, null, 2)} as const;\n` +
    'export type IconName = keyof typeof ICON_PATHS;\n',
);

// Tokens: `:root, [data-theme="<first>"]` colours and shadows, a block per further theme,
// then `:root` for every other family and the font families, then one class per type style.
const t = JSON.parse(readFileSync(src('tokens.json'), 'utf8'));
const themes = t.color.themes.map((x) => x.id);
const first = themes[0];
const val = (v, theme) => (typeof v === 'string' ? v : v[theme] ?? v[first]);
const ref = (v) => (typeof v === 'string' && /^\{[^}]+\}$/.test(v) ? `var(--${v.slice(1, -1)})` : v);
const themed = [...t.color.tokens, ...(t.shadow?.tokens ?? [])];
let css = '/* Generated by scripts/build.mjs from source/tokens.json. Do not edit. */\n';
themes.forEach((theme, i) => {
  const sel = i === 0 ? `:root, [data-theme="${theme}"]` : `[data-theme="${theme}"]`;
  const lines = themed
    .filter((tok) => i === 0 || typeof tok.value !== 'string' || tok.value.startsWith('{'))
    .map((tok) => `  --${tok.name}: ${ref(val(tok.value, theme))};`);
  css += `${sel} {\n${i === 0 ? '  color-scheme: light;\n' : `  color-scheme: ${theme};\n`}${lines.join('\n')}\n}\n`;
});
const plain = Object.entries(t)
  .filter(([k, v]) => !['color', 'shadow', 'type', 'meta'].includes(k) && v && Array.isArray(v.tokens))
  .flatMap(([, v]) => v.tokens);
css += `:root {\n${plain.map((tok) => `  --${tok.name}: ${tok.value};`).join('\n')}\n`;
css += `${Object.entries(t.type.families).map(([k, v]) => `  --font-${k}: ${v};`).join('\n')}\n}\n`;
const px = (v) => (typeof v === 'number' ? `${v}px` : v);
for (const g of t.type.groups) {
  for (const s of g.styles) {
    const fam = s.family ?? g.family;
    css += `.${s.name} { font-family: var(--font-${fam}); font-size: ${px(s.fontSize)}; line-height: ${s.lineHeight}; font-weight: ${s.fontWeight};${s.letterSpacing ? ` letter-spacing: ${s.letterSpacing};` : ''}${s.fontFeatureSettings ? ` font-feature-settings: ${s.fontFeatureSettings};` : ''} }\n`;
  }
}
writeFileSync(join(dist, 'tokens.css'), css);
copyFileSync(src('bundle.css'), join(dist, 'bundle.css'));
writeFileSync(join(dist, 'styles.css'), '@import "./tokens.css";\n@import "./bundle.css";\n');
// One flat stylesheet (font @import hoisted first, then tokens, then components) for consumers that can't follow @import.
const bundleCss = readFileSync(src('bundle.css'), 'utf8');
const fontImports = bundleCss.match(/^@import url\([^)]*\);\s*$/gm) ?? [];
writeFileSync(
  join(dist, 'ulpin.css'),
  `${fontImports.join('\n')}\n${css}\n${fontImports.reduce((s, imp) => s.replace(imp, ''), bundleCss)}`,
);

// JS
await build({
  entryPoints: [join(root, 'src/index.ts')],
  outfile: join(dist, 'index.js'),
  bundle: true,
  format: 'esm',
  jsx: 'automatic',
  target: 'es2020',
  external: ['react', 'react-dom', 'react/jsx-runtime'],
  logLevel: 'warning',
});

// Types
execFileSync(join(root, 'node_modules/.bin/tsc'), ['-p', join(root, 'tsconfig.json')], { stdio: 'inherit' });
console.log('built dist/');
