import { createHash, randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { test, expect } from '@playwright/test';
import { cameraDelta, readCamera } from './usp-camera';

const receiptFile = process.env.ULPIN_D1_RECEIPT_FILE;
test.skip(!receiptFile, 'Requires the real byte-pinned D1 import and isolated services');

test('real D1 roof keeps source identity and absent interiors in the shared Studio map', async ({ page, request }, info) => {
  const receipt = JSON.parse(await readFile(receiptFile!, 'utf8'));
  expect(receipt.schemaVersion).toBe('usp-d1-import-receipt/1');
  const dossierResponse = await request.get(`/api/v1/buildings/${receipt.featureId}/dossier`);
  expect(dossierResponse.ok()).toBe(true);
  const dossier = await dossierResponse.json();
  expect(dossier.building.height.value).toBeNull();
  expect(dossier.records.filter((record: { kind: string }) => ['floor', 'space'].includes(record.kind))).toHaveLength(0);
  const path = `/api/v1/spatial/core/areas/${receipt.areaId}/external/${receipt.featureId}`;
  const query = `?revision=${dossier.building.revision}&sha256=${receipt.sourceSha256}`;
  const result = await request.get(path + query);
  expect(result.status()).toBe(200);
  const resource = await result.json();
  expect(resource.source.id).toBe(receipt.sourceRevisionId);
  expect(resource.source.sha256).toBe(receipt.sourceSha256);
  expect(resource.scene.sourceBuildingId).toBe(receipt.sourceBuildingId);
  expect(resource.scene.lod).toBe('2.2');
  expect(resource.scene.faces).toHaveLength(19);
  expect(resource.scene.faces.map((face: { sourceFaceIndex: number }) => face.sourceFaceIndex)).toEqual(Array.from({ length: 19 }, (_, index) => index));
  expect(resource.scene.faces.filter((face: { surfaceType: string }) => face.surfaceType === 'RoofSurface')).toHaveLength(3);
  expect(resource.scene.interiors).toBe('unavailable');
  expect(resource.scene.frame.globalPlacement).toBe('unqualified');
  const original = await request.get(`/api/v1/sources/${receipt.sourceRevisionId}/file`);
  expect(original.ok()).toBe(true);
  expect(createHash('sha256').update(await original.body()).digest('hex')).toBe(receipt.sourceSha256);
  expect((await request.get(path + query + '&revision=2')).status()).toBe(400);
  expect((await request.get(path + query.replace('revision=' + dossier.building.revision, 'revision=99'))).status()).toBe(409);
  expect((await request.get(path.replace(receipt.areaId, randomUUID()) + query)).status()).toBe(404);
  expect((await request.get(path + query, { headers: { origin: 'https://unapproved.example' } })).status()).toBe(403);

  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(`/studio/areas/${receipt.areaId}`);
  const scene = page.locator('[data-external-canvas]');
  await expect(scene).toHaveAttribute('data-scene-ready', 'true');
  await expect(page.locator('[data-map-runtime-id]')).toHaveCount(1);
  await expect(page.locator('[data-external-roof]')).toHaveAttribute('data-source-sha256', receipt.sourceSha256);
  await page.getByRole('link', { name: '© 3DBAG by tudelft3d and 3DGI · CC BY 4.0', exact: true }).click({ trial: true });
  await page.screenshot({ path: info.outputPath('d1-roof-desktop.png') });
  const canvas = scene.locator('canvas'), box = (await canvas.boundingBox())!;
  const visibleImage = await canvas.screenshot();
  const beforeLayers = await readCamera(scene);
  await page.getByRole('button', { name: 'Layers', exact: true }).click();
  await page.getByLabel('Map layers and properties', { exact: true }).getByRole('button', { name: 'Layers', exact: true }).click();
  await page.getByLabel('Show buildings', { exact: true }).uncheck();
  await expect(scene).toHaveAttribute('data-visible', 'false');
  await page.getByRole('button', { name: 'Close dialog', exact: true }).click();
  expect((await canvas.screenshot()).equals(visibleImage)).toBe(false);
  await expect.poll(async () => cameraDelta(beforeLayers, await readCamera(scene))).toBeLessThan(1);
  await expect(page.locator('[data-map-runtime-id]')).toHaveCount(1);
  await page.getByRole('button', { name: 'Layers', exact: true }).click();
  await page.getByLabel('Map layers and properties', { exact: true }).getByRole('button', { name: 'Layers', exact: true }).click();
  await page.getByLabel('Show buildings', { exact: true }).check();
  await page.getByText('Layer appearance', { exact: true }).click();
  await page.getByLabel('Buildings opacity', { exact: true }).press('Home');
  await expect.poll(async () => Number(await scene.getAttribute('data-opacity'))).toBeLessThan(.06);
  await page.getByLabel('Buildings opacity', { exact: true }).press('End');
  await expect(scene).toHaveAttribute('data-opacity', '1');
  await page.getByRole('button', { name: 'Close dialog', exact: true }).click();
  await expect(scene).toHaveAttribute('data-visible', 'true');
  await expect.poll(async () => cameraDelta(beforeLayers, await readCamera(scene))).toBeLessThan(1);
  await page.mouse.click(box.x + box.width * .5, box.y + box.height * .5);
  await expect(page).toHaveURL(new RegExp(`feature=${receipt.featureId}`));
  const picked = JSON.parse((await scene.getAttribute('data-picked-surface'))!);
  const pickedFace = resource.scene.faces.find((face: { partId: string; sourceFaceIndex: number }) => face.partId === picked.sourcePartId && face.sourceFaceIndex === picked.sourceFaceIndex);
  expect(pickedFace.semanticIndex).toBe(picked.semanticIndex);
  await page.getByRole('button', { name: 'Inspect floors & units' }).click();
  await expect(page.locator('.quick-records')).toContainText('Interior records not supplied');
  await expect(page.locator('[data-record-id]')).toHaveCount(0);
  await page.screenshot({ path: info.outputPath('d1-unavailable-interiors.png') });
  await page.getByRole('button', { name: 'Close inspector', exact: true }).click();
  await page.getByRole('button', { name: 'Fit block', exact: true }).click();
  const movedBox = (await canvas.boundingBox())!, camera = await readCamera(scene);
  await page.mouse.move(movedBox.x + movedBox.width * .5, movedBox.y + movedBox.height * .5);
  await page.mouse.down({ button: 'right' });
  await page.mouse.move(movedBox.x + movedBox.width * .6, movedBox.y + movedBox.height * .56, { steps: 12 });
  await page.mouse.up({ button: 'right' });
  await expect.poll(async () => cameraDelta(camera, await readCamera(scene))).toBeGreaterThan(100);
  const orbited = await readCamera(scene);
  await page.mouse.wheel(0, -100);
  await expect.poll(async () => cameraDelta(orbited, await readCamera(scene))).toBeGreaterThan(100);
  let settled = await readCamera(scene);
  await expect.poll(async () => {
    const current = await readCamera(scene), stable = cameraDelta(settled, current) < 1;
    settled = current; return stable;
  }, { intervals: [100, 200, 400] }).toBe(true);
  await page.getByRole('button', { name: 'Inspector', exact: true }).click();
  await expect.poll(async () => cameraDelta(settled, await readCamera(scene))).toBeLessThan(1);
  await page.getByRole('button', { name: 'Close inspector', exact: true }).click();
  await expect.poll(async () => cameraDelta(settled, await readCamera(scene))).toBeLessThan(1);
  await page.reload();
  await expect(scene).toHaveAttribute('data-scene-ready', 'true');
  await expect(page).toHaveURL(new RegExp(`feature=${receipt.featureId}`));
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByLabel('Selected scope')).toContainText('1655100000500568');
  await expect(page.locator('.quick-records')).toContainText('Interior records not supplied');
  await page.screenshot({ path: info.outputPath('d1-mobile-interiors.png') });
  await page.getByRole('button', { name: 'Close inspector', exact: true }).click();
  await page.getByRole('button', { name: 'Fit block', exact: true }).click();
  await page.getByRole('link', { name: '© 3DBAG by tudelft3d and 3DGI · CC BY 4.0', exact: true }).click({ trial: true });
  await page.screenshot({ path: info.outputPath('d1-mobile-roof.png') });
  expect(errors).toEqual([]);
  await info.attach('d1-lineage-and-capability', { body: JSON.stringify({ receipt, resource,
    rendering: 'local engineering display; software WebGL is not a GPU performance qualification' }, null, 2), contentType: 'application/json' });
});
