/** Bounded measurement mode of the existing guarded semantic-source harness. */
import assert from 'node:assert/strict';
import {execFile,execFileSync} from 'node:child_process';
import {promisify} from 'node:util';
import {readFileSync,writeFileSync} from 'node:fs';
import {open} from 'node:fs/promises';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
const delay=ms=>new Promise(r=>setTimeout(r,ms)),exec=promisify(execFile),GiB=1024**3;
const budgets=Object.freeze({uploadFinalizationMs:90000,firstUsefulMs:30000,semanticClosureMs:120000,finalCatalogMs:180000,tileP95Ms:750,pickP95Ms:750,totalDockerMemoryBytes:5*GiB,ownedProcessRssBytes:1.5*GiB,pairStorageGrowthBytes:4*GiB});
const usageBytes=s=>{const m=s.trim().match(/^([\d.]+)\s*([KMGT]?i?B)$/);assert(m,'Unknown Docker memory unit');return Number(m[1])*({B:1,kB:1000,KB:1000,MB:1e6,GB:1e9,TB:1e12,KiB:1024,MiB:1024**2,GiB,TiB:1024**4}[m[2]]);};
const p95=values=>[...values].sort((a,b)=>a-b)[Math.ceil(values.length*.95)-1];
export async function qualifySemanticScale(c){
  const {root,dir,owner,env,safeEnv,scope,sourceCheck,source,profile,original,member,receipt,db,api,until,decode,hash,runtime,crash,control,recoveryOnly=false}=c,base=env.ULPIN_TEST_URL+'api/v1';
  const command=(program,args)=>execFileSync(program,args,{cwd:root,env:{...safeEnv,...env},encoding:'utf8',timeout:10000,maxBuffer:512*1024}).trim();
  const ids=command('docker',['ps','-q']).split('\n').filter(Boolean),containers=command('docker',['inspect','--format','{"id":{{json .Id}},"name":{{json .Name}},"image":{{json .Image}},"command":{{json .Config.Cmd}},"mounts":{{json .Mounts}}}',...ids]).split('\n').map(JSON.parse),owned=containers.filter(v=>v.name.startsWith('/'+scope.project+'-'));
  assert.equal(owned.length,5);assert(owned.find(v=>v.name.endsWith('-worker-1')).command.includes('--concurrency=2'));
  const initial=(await db.query(`SELECT (SELECT count(*) FROM sources)::int sources,(SELECT count(*) FROM jobs)::int jobs,(SELECT count(*) FROM administrative_unit_observations)::int observations,(SELECT count(*) FROM usp_display.source_semantic_preparations)::int preparations,(SELECT count(*) FROM usp_display.source_tile_generations)::int generations`)).rows[0];assert(Object.values(initial).every(v=>v===0),'Application-cold runtime already has source derivatives');
  const clockBefore=Date.now(),dbClock=(await db.query('SELECT clock_timestamp() now')).rows[0].now.getTime(),dbOffsetMs=dbClock-(clockBefore+Date.now())/2;
  const mvtContract=readFileSync(join(root,'packages/contracts/src/usp/private-mvt.ts'),'utf8'),semanticContract=readFileSync(join(root,'packages/contracts/src/usp/semantic-chunks.ts'),'utf8'),leaseCode=readFileSync(join(root,'packages/server/src/modules/usp/jobs.ts'),'utf8');
  const capacity={historyLimit:Number(mvtContract.match(/completed:(\d+)/)[1]),milestones:Number(semanticContract.match(/displayMilestones:(\d+)/)[1]),configuredLeaseSeconds:Number(leaseCode.match(/LEASE_SECONDS = (\d+)/)[1]),existing:(await db.query(`SELECT count(*)::int jobs,count(*) FILTER(WHERE j.status IN('queued','running','succeeded') OR EXISTS(SELECT 1 FROM usp_display.source_tile_generations g WHERE g.job_id=j.id))::int history FROM jobs j WHERE j.operation='private-mvt'`)).rows[0],reserved:Number((await db.query(`SELECT count(*)::int count FROM operations o CROSS JOIN LATERAL jsonb_each(o.result->'outcomes') s WHERE o.kind='stream-display-capacity' AND s.value->>'state'='reserved'`)).rows[0].count)};assert.equal(capacity.historyLimit,8);assert.equal(capacity.milestones,3);assert.equal(capacity.configuredLeaseSeconds,180);assert(capacity.existing.history+capacity.reserved+capacity.milestones<=capacity.historyLimit,'Fresh recovery cannot reserve its unchanged three slots');
  const plan={capacity,model:{configured:'GPT-6 Sol',reasoning:'max',requestedTier:'default',observedTier:'not exposed'},processorTree:command('git',['rev-parse','HEAD:services/geo']),parserSha256:hash(readFileSync(join(root,'services/geo/geo/projected_vector.py'))),sourceProfileSha256:hash(readFileSync(join(root,'fixtures/usp/D3/nwic-boundaries-v1/vector-admission-profile.json'))),version:recoveryOnly?'semantic-natural-recovery-plan/1':'semantic-scale-plan/1',createdAt:new Date().toISOString(),codeCommit:owner.baseCommit,nonce:owner.nonce,source:original,member,features:733,positions:3125505,geography:profile.crsDiagnostic.finiteTransformedExtentLongitudeLatitude,sourceCrs:'EPSG:7755',targetCrs:'EPSG:4326',axis:'always_xy',verticalReference:null,
    workload:{normalImports:recoveryOnly?[]:['application-cold fresh source','same-input warm new legitimate upload/source intent'],naturalRecoveryImports:1,sequentialTileReadsPerImport:recoveryOnly?0:20,sequentialCanonicalPicksPerImport:recoveryOnly?0:20,osCachesFlushed:false,oneTestLane:true},budgets:recoveryOnly?{initialPrefixObservationMs:120000,configuredLeaseSeconds:180,recoveryAfterCapturedExpiryMs:120000}:budgets,hardware:{hostModel:command('sysctl',['-n','hw.model']),hostCpu:command('sysctl',['-n','machdep.cpu.brand_string']),hostMemoryBytes:Number(command('sysctl',['-n','hw.memsize'])),hostOs:command('sw_vers',['-productVersion']),docker:JSON.parse(command('docker',['info','--format','{"cpus":{{.NCPU}},"memoryBytes":{{.MemTotal}},"version":"{{.ServerVersion}}"}']))},
    containers:containers.map(({id,name,image,command})=>({id,name,image,command})),concurrency:{ownedDispatcherProcesses:1,dispatcherDispatchSelectionLimit:12,celeryWorkerProcesses:2,privateMvtActiveLimit:1,normalImportLanes:1,httpMeasurementConcurrency:1},coResidentServing:'localhost3188 and ulpin/ulpin-repo containers remain running; all running Docker containers are included in sampled total',sampling:{enabled:!recoveryOnly,intervalMs:2000,description:'Docker no-stream snapshots and owned process-group RSS; observed maxima are not peaks'},initial,dbOffsetMs,programSha256:hash(readFileSync(join(root,'scripts/usp/semantic-scale.mjs')))};
  assert.equal(plan.hardware.docker.cpus,4);assert(plan.hardware.docker.memoryBytes<=6*GiB);
  writeFileSync(join(dir,recoveryOnly?'semantic-natural-recovery-plan.json':'semantic-scale-plan.json'),JSON.stringify(plan,null,2)+'\n',{flag:'wx',mode:0o600});Object.assign(receipt,{version:recoveryOnly?'semantic-natural-recovery/1':'semantic-scale/1',plan,normal:[],sampling:{samples:[],errors:[]},notQualified:['Frontend/GPU/3D/city/public/multiuser/replica performance','Survey/legal/currentness/property/rights/height accuracy or provider/training permissions','Changed official geometry or deletion from a second issuing revision','Complete GF-STREAM/GF-SCALE release claims require lead evidence reconciliation/review']});
  const volumes=[];for(const container of owned)for(const mount of container.mounts)if(mount.Type==='volume'&&!volumes.some(v=>v.name===mount.Name))volumes.push({container:container.id,name:mount.Name,path:mount.Destination});assert.equal(volumes.length,3);
  async function storage(){const values=[];for(const v of volumes){const bytes=Number(command('docker',['exec',v.container,'du','-sk',v.path]).split(/\s+/)[0])*1024;assert(Number.isSafeInteger(bytes));values.push({name:v.name,bytes});}return {at:new Date().toISOString(),volumes:values,bytes:values.reduce((a,v)=>a+v.bytes,0)};}
  let sampling=!recoveryOnly;
  async function samples(){while(sampling){try{const at=Date.now(),[docker,processes]=await Promise.all([exec('docker',['stats','--no-stream','--format','{"id":"{{.ID}}","usage":"{{.MemUsage}}"}'],{env:{...safeEnv,...env},timeout:10000,maxBuffer:128*1024}),exec('ps',['-axo','pid=,pgid=,rss='],{env:safeEnv,timeout:3000,maxBuffer:512*1024})]);
    const groups=['api','dispatcher'].map(label=>JSON.parse(readFileSync(join(dir,label+'.group.json'))).pgid),rss=processes.stdout.trim().split('\n').map(v=>v.trim().split(/\s+/).map(Number)).filter(v=>groups.includes(v[1])).reduce((a,v)=>a+v[2]*1024,0),usage=docker.stdout.trim().split('\n').filter(Boolean).map(JSON.parse),jobs=(await db.query("SELECT operation,count(*)::int count FROM jobs WHERE status IN ('queued','running') GROUP BY operation")).rows;
    receipt.sampling.samples.push({at:new Date(at).toISOString(),durationMs:Date.now()-at,totalDockerMemoryBytes:usage.reduce((a,v)=>a+usageBytes(v.usage.split('/')[0]),0),dockerContainers:usage.length,ownedProcessRssBytes:rss,activeJobs:jobs});
    }catch(e){receipt.sampling.errors.push(String(e.message).slice(0,200));}if(sampling)await delay(2000);}}
  const sampler=recoveryOnly?Promise.resolve():samples();
  async function retain(label){receipt.phase=label+'-upload';console.log(JSON.stringify({phase:receipt.phase}));const {caseId}=await api('/source-cases',201,{requestKey:randomUUID(),name:'NWIC '+label+' bounded backend qualification'}),started=Date.now();
    let upload=await api(`/ingestion/cases/${caseId}/uploads`,201,{requestKey:randomUUID(),expectedCaseRevision:0,filename:'district_nwic_geojson.zip',mediaType:'application/zip',bytes:source.bytes,sha256:source.sha256,provenance:{issuer:sourceCheck.source.issuer,originalUrl:source.finalUrl,acquiredAt:new Date(source.acquiredAtUtc).toISOString(),permissionReference:sourceCheck.termsDecision.termsUrl,limitations:['Administrative context; source accuracy/currentness/legal and training permission unqualified']}});
    const file=await open(source.privateOriginalPath,'r');try{for(let part=1;part<=upload.partCount;part++){const offset=(part-1)*upload.partBytes,bytes=Buffer.alloc(Math.min(upload.partBytes,source.bytes-offset));assert.equal((await file.read(bytes,0,bytes.length,offset)).bytesRead,bytes.length);upload=await api(`/ingestion/cases/${caseId}/uploads/${upload.id}/parts/${part}`,200,bytes,'PUT',{'X-Request-Key':randomUUID(),'X-Upload-Revision':String(upload.revision),'X-Case-Revision':String(upload.currentCaseRevision),'X-Part-Sha256':hash(bytes)});}}finally{await file.close();}
    upload=await api(`/ingestion/cases/${caseId}/uploads/${upload.id}/finalize`,200,{requestKey:randomUUID(),expectedRevision:upload.revision,expectedCaseRevision:upload.currentCaseRevision,sha256:source.sha256});assert.equal(upload.state,'retained');
    const common=`/ingestion/cases/${caseId}/sources/${upload.source.sourceId}`;return {caseId,sourceId:upload.source.sourceId,uploadId:upload.id,uploadFinalizationMs:Date.now()-started,path:common+'/projected-vector',tiles:common+'/private-mvt',request:{requestKey:randomUUID(),expectedCaseRevision:upload.currentCaseRevision,expectedSourceRevision:1,sourceSha256:source.sha256,semanticChunks:'nwic-semantic-chunks/1'}};}
  async function queue(input){const queued=await api(input.path,202,input.request),job=(await db.query('SELECT created_at,input_fingerprint FROM jobs WHERE id=$1',[queued.jobId])).rows[0];input.jobId=queued.jobId;input.queuedAt=job.created_at.toISOString();input.inputFingerprint=job.input_fingerprint;const replay=await api(input.path,202,input.request);assert.equal(replay.jobId,queued.jobId);input.idempotentReplay={jobId:replay.jobId,sameRequestKey:true,countsAsImport:false};}
  const elapsed=input=>Math.round(Date.now()+dbOffsetMs-new Date(input.queuedAt).getTime());
  async function tileAndPick(input,manifest,deadline){const timeout=()=>{if(deadline===undefined)return 15000;const ms=Math.floor(deadline-Date.now()-dbOffsetMs);assert(ms>0,'Tile/pick observation deadline expired');return Math.min(15000,ms);};const cell=manifest.manifest.cells.find(v=>v.emitted>0);assert(cell);const prefix=input.tiles+`/generations/${manifest.pin.jobId}/${manifest.pin.version}/tiles/${cell.cell.z}/${cell.cell.x}/${cell.cell.y}`,response=await fetch(base+prefix+'.mvt',{signal:AbortSignal.timeout(timeout())});assert.equal(response.status,200);const bytes=Buffer.from(await response.arrayBuffer());assert.equal(hash(bytes),cell.tile.sha256);const features=decode(bytes);assert.equal(features.length,cell.emitted);const feature=features[0],lookup=deadline===undefined?await api(prefix+'/units/'+feature.unitId):await api(prefix+'/units/'+feature.unitId,200,undefined,undefined,{},timeout());assert.equal(lookup.observation.id,feature.unitId);assert.equal(lookup.mvtId,feature.id);return {cell:cell.cell,tileBytes:bytes.length,tileSha256:cell.tile.sha256,feature,prefix};}
  async function finish(input,sourceDeadline,tileDeadline=sourceDeadline){const remaining=deadline=>{const ms=Math.floor(deadline-Date.now()-dbOffsetMs);assert(ms>0,'Fixed observation deadline expired');return ms;},boundedApi=(path,deadline)=>api(path,200,undefined,undefined,{},Math.min(150000,remaining(deadline)));const sourceStatus=await until(async()=>{const s=await boundedApi(input.path,sourceDeadline);assert(!['failed','stale'].includes(s.status),'Source failed: '+s.errorCode);return s.status==='succeeded'?s:null;},remaining(sourceDeadline)/1000);input.semanticClosureMs=elapsed(input);input.sourceClosureObservedAt=new Date().toISOString();input.sourceClosureTotals=sourceStatus.totals;assert.equal(sourceStatus.coverage.remainingRecords,0);assert.deepEqual(sourceStatus.totals,{features:733,positions:3125505,nativeValid:720,nativeInvalid:13,admitted:720,quarantined:13});
    const final=sourceStatus.displayMilestones.find(v=>v.phase==='final');assert(final?.jobId);const tileStatus=await until(async()=>{const s=await boundedApi(input.tiles,tileDeadline);assert(!['failed','stale'].includes(s.status),'Final tiles failed: '+s.errorCode);return s.jobId===final.jobId&&s.status==='succeeded'&&s.generation?s:null;},remaining(tileDeadline)/1000),manifest=await boundedApi(input.tiles+`/generations/${final.jobId}/${tileStatus.generation.version}`,tileDeadline);input.finalCatalogMs=elapsed(input);input.finalCatalogObservedAt=new Date().toISOString();input.displayMilestones=(await boundedApi(input.path,tileDeadline)).displayMilestones;assert(manifest.manifest.complete);assert.equal(manifest.manifest.cells.length,62);assert.equal(manifest.manifest.sourceCoverage.state,'complete');input.generation=manifest.pin;
    const prep=(await db.query('SELECT p.created_at,p.sha256,p.body FROM usp_display.source_semantic_preparations p WHERE job_id=$1',[input.jobId])).rows[0];input.preparation={createdAt:prep.created_at.toISOString(),timestampMeaning:'SQL transaction creation/default now(), not observed commit',transactionCreatedElapsedFromQueueMs:Math.round(prep.created_at.getTime()-new Date(input.queuedAt).getTime()),processorExecutionSeconds:prep.body.result.execution.seconds,sha256:prep.sha256,partitions:prep.body.partitions.length};return manifest;}
  async function viewport(input,manifest){const cells=manifest.manifest.cells.filter(v=>v.emitted>0).slice(0,20);assert.equal(cells.length,20);const tiles=[],picks=[];for(const cell of cells){const prefix=input.tiles+`/generations/${manifest.pin.jobId}/${manifest.pin.version}/tiles/${cell.cell.z}/${cell.cell.x}/${cell.cell.y}`,start=performance.now(),r=await fetch(base+prefix+'.mvt',{signal:AbortSignal.timeout(15000)});assert.equal(r.status,200);const bytes=Buffer.from(await r.arrayBuffer());tiles.push(performance.now()-start);assert.equal(hash(bytes),cell.tile.sha256);const f=decode(bytes)[0];assert(f);const pickedAt=performance.now(),lookup=await api(prefix+'/units/'+f.unitId);picks.push(performance.now()-pickedAt);assert.equal(lookup.observation.id,f.unitId);assert.equal(lookup.mvtId,f.id);}
    receipt.phase='viewport-'+input.jobId;input.viewport={sequential:true,actualCells:cells.map(v=>v.cell),tileMs:tiles,pickMs:picks,tileP95Ms:p95(tiles),pickP95Ms:p95(picks),errors:0};assert(input.viewport.tileP95Ms<=budgets.tileP95Ms,'Viewport tile p95 budget exceeded');assert(input.viewport.pickP95Ms<=budgets.pickP95Ms,'Canonical pick p95 budget exceeded');}
  try{
    if(!recoveryOnly){receipt.storageBeforePair=await storage();let prior;
    for(const label of ['application-cold','same-input-warm']){const input=await retain(label);receipt.normal.push(input);assert(input.uploadFinalizationMs<=budgets.uploadFinalizationMs,'Upload/finalization budget exceeded');await queue(input);receipt.phase=label+'-import';console.log(JSON.stringify({phase:receipt.phase,jobId:input.jobId}));
      const first=await until(async()=>{const s=await api(input.path);assert(!['failed','stale'].includes(s.status),'Source failed: '+s.errorCode);const milestone=s.displayMilestones?.find(v=>v.phase==='early');assert(milestone?.state!=='unavailable','Early tile unavailable: '+milestone?.errorCode);if(!milestone?.jobId)return null;const t=await api(input.tiles);if(!t.generation)return null;const m=await api(input.tiles+`/generations/${milestone.jobId}/${t.generation.version}`);return m.manifest.cells.some(v=>v.emitted>0)?{s,m}:null;},30);
      const pick=await tileAndPick(input,first.m),snapshot=(await db.query(`SELECT j.status,(SELECT count(*)::int FROM administrative_unit_observations WHERE job_id=j.id) records,(SELECT count(*)::int FROM usp_display.source_semantic_chunks WHERE job_id=j.id) chunks FROM jobs j WHERE id=$1`,[input.jobId])).rows[0];input.firstUseful={elapsedFromQueueMs:elapsed(input),generation:first.m.pin,coverage:first.m.manifest.sourceCoverage,...pick,sourceAtRead:snapshot};assert.equal(snapshot.status,'running');assert(snapshot.records<733);assert(input.firstUseful.elapsedFromQueueMs<=budgets.firstUsefulMs,'First useful tile/pick budget exceeded');
      const manifest=await finish(input,new Date(input.queuedAt).getTime()+budgets.semanticClosureMs,new Date(input.queuedAt).getTime()+budgets.finalCatalogMs);assert(input.semanticClosureMs<=budgets.semanticClosureMs,'Semantic closure budget exceeded');assert(input.finalCatalogMs<=budgets.finalCatalogMs,'Final catalog budget exceeded');await viewport(input,manifest);
      const records=(await db.query(`SELECT feature_index,unit_id,raw_ref->>'sha256' raw_sha,geographic_ref->>'sha256' geo_sha FROM administrative_unit_observations WHERE job_id=$1 ORDER BY feature_index`,[input.jobId])).rows;
      if(prior){assert.notEqual(input.sourceId,prior.sourceId);assert.notEqual(input.jobId,prior.jobId);input.reuse={newLegitimateSourceIntent:true,sourceByteHashEqual:true,canonicalUnitIds:records.filter((v,i)=>v.unit_id===prior.records[i].unit_id).length,rawArtifactHashes:records.filter((v,i)=>v.raw_sha===prior.records[i].raw_sha).length,geographicArtifactHashes:records.filter((v,i)=>v.geo_sha!==null&&v.geo_sha===prior.records[i].geo_sha).length};}prior={sourceId:input.sourceId,jobId:input.jobId,records};console.log(JSON.stringify({phase:label+'-complete',firstUsefulMs:input.firstUseful.elapsedFromQueueMs,semanticClosureMs:input.semanticClosureMs,finalCatalogMs:input.finalCatalogMs,tileP95Ms:input.viewport.tileP95Ms,pickP95Ms:input.viewport.pickP95Ms}));}
    receipt.phase='pair-storage-and-resource-budgets';receipt.storageAfterPair=await storage();receipt.pairStorageGrowthBytes=receipt.storageAfterPair.bytes-receipt.storageBeforePair.bytes;assert(receipt.pairStorageGrowthBytes<=budgets.pairStorageGrowthBytes,'Cold/warm pair storage budget exceeded');sampling=false;await sampler;assert.equal(receipt.sampling.errors.length,0,'Resource sampling failed');assert(receipt.sampling.samples.length>=2);
    receipt.sampling.observedMaxDockerMemoryBytes=Math.max(...receipt.sampling.samples.map(v=>v.totalDockerMemoryBytes));receipt.sampling.observedMaxOwnedRssBytes=Math.max(...receipt.sampling.samples.map(v=>v.ownedProcessRssBytes));receipt.sampling.maximumStartGapMs=Math.max(...receipt.sampling.samples.slice(1).map((v,i)=>new Date(v.at)-new Date(receipt.sampling.samples[i].at)));assert(receipt.sampling.observedMaxDockerMemoryBytes<=budgets.totalDockerMemoryBytes,'Sampled total Docker memory budget exceeded');assert(receipt.sampling.observedMaxOwnedRssBytes<=budgets.ownedProcessRssBytes,'Sampled owned RSS budget exceeded');}
    const input=await retain('natural-lease-recovery');receipt.naturalRecovery=input;input.healthObservations=[];
    async function health(label){const at=new Date().toISOString(),started=Date.now();let response,body;try{response=await fetch(base+'/health',{signal:AbortSignal.timeout(input.observationDeadline?Math.max(1,Math.min(2000,new Date(input.observationDeadline).getTime()-Date.now()-Math.ceil(dbOffsetMs))):2000)});body=await response.json();}catch(error){input.healthObservations.push({at,label,healthy:false,error:String(error.message)});throw error;}const value={at,label,durationMs:Date.now()-started,status:response.status,ok:body.ok,services:body.services};input.healthObservations.push(value);assert.equal(response.status,200,'Owned API health failed');assert.equal(body.ok,true);assert(['database','storage','processor','redis','worker'].every(key=>body.services?.[key]===true),'An owned dependency was unhealthy');return value;}
    await queue(input);input.reservationAfterQueue=(await db.query("SELECT result FROM operations WHERE case_id=$1 AND kind='stream-display-capacity' AND operation_key=$2",[input.caseId,`stream-display:${input.jobId}`])).rows[0].result;assert.equal(Object.keys(input.reservationAfterQueue.slots).length,capacity.milestones);assert.equal(input.reservationAfterQueue.sourceId,input.sourceId);input.apiIdentityBefore=JSON.parse(readFileSync(join(dir,'api.group.json')));await health('before-fault');
    const firstSeal=await until(async()=>{const rows=(await db.query('SELECT sequence,sha256,body FROM usp_display.source_semantic_chunks WHERE job_id=$1 ORDER BY sequence',[input.jobId])).rows;return rows.length?rows:null;},120);
    const before=(await db.query('SELECT a.*,j.status,(SELECT count(*)::int FROM administrative_unit_observations WHERE job_id=j.id) records,clock_timestamp() observed_at FROM usp_job_attempts a JOIN jobs j ON j.id=a.job_id WHERE a.job_id=$1 ORDER BY a.number DESC LIMIT 1',[input.jobId])).rows[0];
    assert.equal(before.status,'running');assert(before.records<733);assert.equal(before.state,'active');input.attemptBeforeStop={number:before.number,fence:Number(before.fence),owner:before.owner,inputSha256:before.input_sha256,createdAt:before.created_at.toISOString(),leaseUntil:before.lease_until.toISOString(),observedAt:before.observed_at.toISOString(),records:before.records,firstSeal:{sequence:firstSeal[0].sequence,sha256:firstSeal[0].sha256}};
    input.crash=await crash();input.dispatcherGoneObservedAt=new Date().toISOString();const sealed=(await db.query('SELECT sequence,sha256,body FROM usp_display.source_semantic_chunks WHERE job_id=$1 ORDER BY sequence',[input.jobId])).rows;assert(sealed.length>0);input.sealRowsBeforeSha256=hash(JSON.stringify(sealed));
    const a=(await db.query('SELECT * FROM usp_job_attempts WHERE job_id=$1 ORDER BY number DESC LIMIT 1',[input.jobId])).rows[0],old={jobId:input.jobId,number:a.number,fence:Number(a.fence),owner:a.owner,inputSha256:a.input_sha256,leaseUntil:a.lease_until.toISOString()},expiry=a.lease_until.getTime();assert.equal(a.number,before.number);assert.equal(a.owner,before.owner);assert.equal(Number(a.fence),Number(before.fence));
    input.attemptBefore=old;input.attemptCreatedAt=a.created_at.toISOString();input.sealsBefore=sealed.map(v=>({sequence:v.sequence,sha256:v.sha256}));input.configuredLeaseSeconds=capacity.configuredLeaseSeconds;input.outageExcludedFromNormalTimings=true;input.observationDeadline=new Date(expiry+120000).toISOString();
    const early=await api(input.path+`/jobs/${input.jobId}/chunks/${sealed[0].sequence}`);assert.equal(early.pin.sha256,sealed[0].sha256);assert.equal(early.currentSourceAccepted,false);input.earlyPrefixRead={pin:early.pin,coverage:early.chunk.coverage,currentSourceAccepted:early.currentSourceAccepted};
    assert(expiry>Date.now()+dbOffsetMs);receipt.phase='natural-expiry-wait';console.log(JSON.stringify({phase:receipt.phase,jobId:input.jobId,leaseUntil:old.leaseUntil,deadline:input.observationDeadline}));
    let nextHealth=0;input.leaseObservationCount=0;while(true){const row=(await db.query('SELECT clock_timestamp() now,lease_until FROM usp_job_attempts WHERE job_id=$1 AND number=$2',[input.jobId,old.number])).rows[0];input.leaseObservationCount++;assert.equal(row.lease_until.toISOString(),old.leaseUntil,'Lease changed during dispatcher outage');if(row.now.getTime()>expiry){input.expiryObservedAt=row.now.toISOString();break;}if(Date.now()>=nextHealth){await health('dispatcher-outage');nextHealth=Date.now()+15000;}assert(row.now.getTime()<=expiry+120000,'Expiry observation deadline exceeded');await delay(Math.max(1,Math.min(1000,expiry-row.now.getTime()+1)));}
    input.resumeRequestedAt=new Date().toISOString();input.resume=JSON.parse(runtime('dispatcher-resume').trim().split('\n').at(-1));input.resumedAt=new Date().toISOString();input.dispatcherSignalToReadyMs=new Date(input.resumedAt)-new Date(input.crash.at);await health('dispatcher-resumed');input.apiIdentityAfter=JSON.parse(readFileSync(join(dir,'api.group.json')));assert.deepEqual(input.apiIdentityAfter,input.apiIdentityBefore,'API process identity changed during dispatcher outage');receipt.phase='natural-recovery-observation';console.log(JSON.stringify({phase:receipt.phase,jobId:input.jobId}));
    await finish(input,expiry+120000);assert(Date.now()+dbOffsetMs<=expiry+120000,'Natural recovery observation exceeded captured expiry+120s');input.recoveredAfterExpiryMs=Math.round(Date.now()+dbOffsetMs-expiry);input.sourceClosedAfterExpiryMs=Math.round(new Date(input.sourceClosureObservedAt).getTime()+dbOffsetMs-expiry);
    const after=(await db.query('SELECT sequence,sha256,body FROM usp_display.source_semantic_chunks WHERE job_id=$1 ORDER BY sequence',[input.jobId])).rows;assert.equal(hash(JSON.stringify(after.slice(0,sealed.length))),input.sealRowsBeforeSha256,'Committed seals changed during recovery');input.preservedSealRowsAfterSha256=hash(JSON.stringify(after.slice(0,sealed.length)));input.attempts=(await db.query('SELECT number,fence,state FROM usp_job_attempts WHERE job_id=$1 ORDER BY number',[input.jobId])).rows;assert.equal(input.attempts.length,2);assert.equal(input.attempts[1].state,'accepted');
    const acceptedState=async()=>JSON.stringify((await db.query('SELECT j.status,j.completed_at,m.accepted_fence,m.result_ref FROM jobs j JOIN usp_job_metadata m ON m.job_id=j.id WHERE j.id=$1',[input.jobId])).rows[0]);const acceptedBefore=await acceptedState();assert.equal(control('fail',input.jobId,old),false);assert.equal(await acceptedState(),acceptedBefore);input.staleAttemptDenied=true;input.acceptedStateSha256=hash(acceptedBefore);input.sealsAfter=after.map(v=>({sequence:v.sequence,sha256:v.sha256}));assert.equal(after.length,67);
    input.sqlClosure=(await db.query("SELECT count(*)::int total,count(*) FILTER(WHERE disposition='admitted')::int admitted,count(*) FILTER(WHERE disposition='quarantined')::int quarantined,count(*) FILTER(WHERE committed_chunk_sequence IS NULL)::int unsealed FROM administrative_unit_observations WHERE job_id=$1",[input.jobId])).rows[0];assert.deepEqual(input.sqlClosure,{total:733,admitted:720,quarantined:13,unsealed:0});
    input.tileJobs=(await db.query("SELECT j.id,j.status,j.error,(SELECT count(*)::int FROM usp_display.source_tile_generations g WHERE g.job_id=j.id) generations FROM jobs j WHERE j.source_id=$1 AND j.operation='private-mvt' ORDER BY j.created_at",[input.sourceId])).rows;assert.equal(input.tileJobs.length,3);input.finalTileAndPick=await tileAndPick(input,await api(input.tiles+`/generations/${input.generation.jobId}/${input.generation.version}`,200,undefined,undefined,{},Math.max(1,Math.floor(expiry+120000-Date.now()-dbOffsetMs))),expiry+120000);
    const preserved=await api(input.path+`/jobs/${input.jobId}/chunks/${sealed[0].sequence}`,200,undefined,undefined,{},Math.max(1,Math.floor(expiry+120000-Date.now()-dbOffsetMs)));assert.equal(preserved.pin.sha256,sealed[0].sha256);assert.equal(preserved.currentSourceAccepted,true);input.earlyPrefixStillAccepted=true;await health('recovery-complete');input.observationFinishedAt=new Date().toISOString();assert(Date.now()+dbOffsetMs<=expiry+120000,'Final recovery checks exceeded captured expiry+120s');
    assert.equal((await db.query('SELECT count(*)::int count FROM usp_model_calls')).rows[0].count,0);receipt.status='passed';receipt.finishedAt=new Date().toISOString();console.log(JSON.stringify({status:'passed',receipt:join(dir,recoveryOnly?'semantic-natural-recovery.json':'semantic-scale.json'),naturalRecoveredAfterExpiryMs:input.recoveredAfterExpiryMs}));
  }catch(error){receipt.status='failed';receipt.failure={name:error.name,message:error.message};throw error;}
  finally{sampling=false;await sampler;if(receipt.sampling.samples.length){receipt.sampling.observedMaxDockerMemoryBytes=Math.max(...receipt.sampling.samples.map(v=>v.totalDockerMemoryBytes));receipt.sampling.observedMaxOwnedRssBytes=Math.max(...receipt.sampling.samples.map(v=>v.ownedProcessRssBytes));receipt.sampling.maximumStartGapMs=Math.max(0,...receipt.sampling.samples.slice(1).map((v,i)=>new Date(v.at)-new Date(receipt.sampling.samples[i].at)));}receipt.finishedAt=new Date().toISOString();}
}
