import assert from 'node:assert/strict';
import test from 'node:test';
import { cp, mkdtemp, readFile, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { parseUsp, UspDataPackSchema } from '../packages/contracts/src/usp/index';
import { verifyUspPack } from '../scripts/usp/data/verify-pack';

const root = path.resolve('fixtures/usp/D0/contract-smoke');
const fresh = async (): Promise<any> => JSON.parse(await readFile(path.join(root, 'manifest.json'), 'utf8'));
const invalid = (input: unknown) => assert.throws(() => parseUsp(UspDataPackSchema, input));
const pass = { status: 'passed', evidenceRef: 'authored-test-receipt' };

test('the authored manifest parses and actually preserved files match every hash', async () => {
  const raw = await fresh();
  const parsed = parseUsp(UspDataPackSchema, raw);
  assert.deepEqual(JSON.parse(JSON.stringify(parsed)), raw);
  const result = await verifyUspPack(path.join(root, 'manifest.json'));
  assert.equal(result.checked.length, 3); assert.equal(result.unavailable.length, 0);
  assert.equal(result.profile, 'contract-smoke');
  assert.match(result.qualification, /no parsing/);
  assert.deepEqual(await fresh(), raw, 'verification must not promote stored stages or modify data');
});
test('source values and independent expected results are not generated by our parser', async () => {
  const csv = await readFile(path.join(root, 'records.csv'), 'utf8');
  const expected = JSON.parse(await readFile(path.join(root, 'expected.json'), 'utf8'));
  assert.ok(csv.includes('\n000127,U-A101,'));
  assert.equal(expected.literalParcelId, '000127');
  assert.equal(expected.geometryOracles[0].expectedPositiveVolumeM3, 20);
  assert.equal(expected.geometryOracles[2].expectedAreaM2, 96);
});
for (const assetPath of ['../outside.csv', '/absolute.csv', 'C:\\records.csv', 'a/../b.csv', 'a//b', './a', 'a\\b']) {
  test(`reject escaping/noncanonical asset path ${assetPath}`, async () => {
    const input = await fresh(); input.assets[0].content.path = assetPath; invalid(input);
  });
}
test('unknown metadata is preserved, not assigned a default datum or metres', async () => {
  const result = parseUsp(UspDataPackSchema, await fresh());
  assert.equal(result.assets[0].reference.verticalReference, null);
  assert.equal(result.assets[0].reference.horizontalUnit, null);
});
test('missing originals can be recorded, but cannot have fabricated successful stages', async () => {
  const input = await fresh();
  input.assets[0].content = { state: 'unavailable', reason: 'Source not obtained' };
  assert.ok(parseUsp(UspDataPackSchema, input));
  input.assets[0].verification.parsed = pass; invalid(input);
});
test('parsing/rendering need earlier evidence; catalogue inspection alone is insufficient', async () => {
  const input = await fresh();
  input.assets[0].verification.catalogue_checked = pass;
  input.assets[0].verification.rendered = pass; invalid(input);
  input.assets[0].verification.bytes_preserved = pass; invalid(input);
  input.assets[0].verification.parsed = pass;
  assert.ok(parseUsp(UspDataPackSchema, input));
});
test('a source-only workflow need not falsely claim 3D rendering', async () => {
  const input = await fresh();
  const v = input.assets[0].verification;
  v.bytes_preserved = pass; v.parsed = pass; v.workflow_verified = pass;
  assert.equal(parseUsp(UspDataPackSchema, input).assets[0].verification.rendered.status, 'not_run');
});
test('successful stage requires an explicit evidence reference', async () => {
  const input = await fresh(); input.assets[0].verification.bytes_preserved = { status: 'passed' }; invalid(input);
});
test('D0 cannot be relabelled as observed survey evidence', async () => {
  const input = await fresh(); input.assets[0].classification = 'observed'; invalid(input);
});
test('expected results must have retained declared bytes and a hash', async () => {
  const input = await fresh(); input.expectedPath = 'undeclared.json'; invalid(input);
});
test('asset identities and contained paths are unique', async () => {
  const input = await fresh(); input.assets[1].id = input.assets[0].id; invalid(input);
  const paths = await fresh(); paths.assets[1].content.path = paths.assets[0].content.path; invalid(paths);
});
test('missing, duplicate, self and cyclic dependencies fail explicitly', async () => {
  for (const deps of [['missing'], ['evidence.txt', 'evidence.txt'], ['records.csv']]) {
    const input = await fresh(); input.assets[0].dependencies = deps; invalid(input);
  }
  const cycle = await fresh(); cycle.assets[0].dependencies = ['evidence.txt']; cycle.assets[1].dependencies = ['records.csv']; invalid(cycle);
});
test('contradictory capability declarations fail', async () => {
  const input = await fresh(); input.missingCapabilities.push(input.expectedCapabilities[0]); invalid(input);
});
for (const url of ['not-a-url', 'http://example.invalid/source', 'https://name:secret@example.invalid/source']) {
  test(`invalid source origin does not escape schema error handling: ${url.split(':')[0]}`, async () => {
    const input = await fresh(); input.assets[0].origin = { kind: 'external', url }; invalid(input);
  });
}
test('external catalogue URLs do not require invented file hashes', async () => {
  const input = await fresh(); input.packId = 'D4';
  input.assets[0].origin = { kind: 'external', url: 'https://example.invalid/source' };
  input.assets[0].content = { state: 'unavailable', reason: 'Not downloaded' };
  assert.ok(parseUsp(UspDataPackSchema, input));
});
async function inCopy(run: (directory: string) => Promise<void>) {
  const directory = await mkdtemp(path.join(tmpdir(), 'ulpin-f0-pack-'));
  try { await cp(root, directory, { recursive: true }); await run(directory); }
  finally { await rm(directory, { recursive: true, force: true }); }
}
test('changed bytes fail integrity validation even when length is unchanged', async () => inCopy(async directory => {
  const file = path.join(directory, 'records.csv');
  const contents = await readFile(file, 'utf8'); await writeFile(file, contents.replace('000127', '999127'));
  await assert.rejects(verifyUspPack(path.join(directory, 'manifest.json')), /hash mismatch/);
}));
test('wrong declared size fails before hashing', async () => inCopy(async directory => {
  const input = await fresh(); input.assets[0].content.bytes += 1;
  await writeFile(path.join(directory, 'manifest.json'), JSON.stringify(input));
  await assert.rejects(verifyUspPack(path.join(directory, 'manifest.json')), /size\/budget mismatch/);
}));
test('symlink assets are not followed', async () => inCopy(async directory => {
  await rm(path.join(directory, 'records.csv'));
  await symlink(path.join(root, 'records.csv'), path.join(directory, 'records.csv'));
  await assert.rejects(verifyUspPack(path.join(directory, 'manifest.json')), /Symlink/);
}));
test('unavailable originals remain an explicit result, not silently fetched', async () => inCopy(async directory => {
  const input = await fresh(); input.assets[0].content = { state: 'unavailable', reason: 'Not obtained' };
  await writeFile(path.join(directory, 'manifest.json'), JSON.stringify(input));
  const result = await verifyUspPack(path.join(directory, 'manifest.json'));
  assert.equal(result.checked.length, 2); assert.equal(result.unavailable.length, 1);
}));
