import assert from 'node:assert/strict';
import test from 'node:test';
import { cp, mkdtemp, readFile, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { parseUsp, UspDataPackSchema } from '../packages/contracts/src/usp/index';
import { verifyUspPack } from '../scripts/usp/data/verify-pack';

const root = path.resolve('fixtures/usp/D0/contract-smoke');
const fresh = async (): Promise<any> => JSON.parse(await readFile(path.join(root, 'manifest.json'), 'utf8'));
const invalid = (input: unknown) => assert.throws(() => parseUsp(UspDataPackSchema, input));
const pass = { status: 'passed', evidenceRef: 'authored-test-receipt' };

test('the authored manifest parses and actually preserved files match every hash', async () => {
  const raw = await fresh();
  const parsed = parseUsp(UspDataPackSchema, raw);
  assert.deepEqual(JSON.parse(JSON.stringify(parsed)), raw);
  const result = await verifyUspPack(path.join(root, 'manifest.json'));
  assert.equal(result.checked.length, 3); assert.equal(result.unavailable.length, 0);
  assert.equal(result.profile, 'contract-smoke');
  assert.match(result.qualification, /no parsing/);
  assert.deepEqual(await fresh(), raw, 'verification must not promote stored stages or modify data');
});
test('source values and independent expected results are not generated by our parser', async () => {
  const csv = await readFile(path.join(root, 'records.csv'), 'utf8');
  const expected = JSON.parse(await readFile(path.join(root, 'expected.json'), 'utf8'));
  assert.ok(csv.includes('\n000127,U-A101,'));
  assert.equal(expected.literalParcelId, '000127');
  assert.equal(expected.geometryOracles[0].expectedPositiveVolumeM3, 20);
  assert.equal(expected.geometryOracles[2].expectedAreaM2, 96);
});
for (const assetPath of ['../outside.csv', '/absolute.csv', 'C:\\records.csv', 'a/../b.csv', 'a//b', './a', 'a\\b']) {
  test(`reject escaping/noncanonical asset path ${assetPath}`, async () => {
    const input = await fresh(); input.assets[0].content.path = assetPath; invalid(input);
  });
}
test('unknown metadata is preserved, not assigned a default datum or metres', async () => {
  const result = parseUsp(UspDataPackSchema, await fresh());
  assert.equal(result.assets[0].reference.verticalReference, null);
  assert.equal(result.assets[0].reference.horizontalUnit, null);
});
test('missing originals can be recorded, but cannot have fabricated successful stages', async () => {
  const input = await fresh();
  input.assets[0].content = { state: 'unavailable', reason: 'Source not obtained' };
  assert.ok(parseUsp(UspDataPackSchema, input));
  input.assets[0].verification.parsed = pass; invalid(input);
});
test('parsing/rendering need earlier evidence; catalogue inspection alone is insufficient', async () => {
  const input = await fresh();
  input.assets[0].verification.catalogue_checked = pass;
  input.assets[0].verification.rendered = pass; invalid(input);
  input.assets[0].verification.bytes_preserved = pass; invalid(input);
  input.assets[0].verification.parsed = pass;
  assert.ok(parseUsp(UspDataPackSchema, input));
});
test('a source-only workflow need not falsely claim 3D rendering', async () => {
  const input = await fresh();
  const v = input.assets[0].verification;
  v.bytes_preserved = pass; v.parsed = pass; v.workflow_verified = pass;
  assert.equal(parseUsp(UspDataPackSchema, input).assets[0].verification.rendered.status, 'not_run');
});
test('successful stage requires an explicit evidence reference', async () => {
  const input = await fresh(); input.assets[0].verification.bytes_preserved = { status: 'passed' }; invalid(input);
});
test('D0 cannot be relabelled as observed survey evidence', async () => {
  const input = await fresh(); input.assets[0].classification = 'observed'; invalid(input);
});
test('expected results must have retained declared bytes and a hash', async () => {
  const input = await fresh(); input.expectedPath = 'undeclared.json'; invalid(input);
});
test('asset identities and contained paths are unique', async () => {
  const input = await fresh(); input.assets[1].id = input.assets[0].id; invalid(input);
  const paths = await fresh(); paths.assets[1].content.path = paths.assets[0].content.path; invalid(paths);
});
test('missing, duplicate, self and cyclic dependencies fail explicitly', async () => {
  for (const deps of [['missing'], ['evidence.txt', 'evidence.txt'], ['records.csv']]) {
    const input = await fresh(); input.assets[0].dependencies = deps; invalid(input);
  }
  const cycle = await fresh(); cycle.assets[0].dependencies = ['evidence.txt']; cycle.assets[1].dependencies = ['records.csv']; invalid(cycle);
});
test('contradictory capability declarations fail', async () => {
  const input = await fresh(); input.missingCapabilities.push(input.expectedCapabilities[0]); invalid(input);
});
for (const url of ['not-a-url', 'http://example.invalid/source', 'https://name:secret@example.invalid/source']) {
  test(`invalid source origin does not escape schema error handling: ${url.split(':')[0]}`, async () => {
    const input = await fresh(); input.assets[0].origin = { kind: 'external', url }; invalid(input);
  });
}
test('external catalogue URLs do not require invented file hashes', async () => {
  const input = await fresh(); input.packId = 'D4';
  input.assets[0].origin = { kind: 'external', url: 'https://example.invalid/source' };
  input.assets[0].content = { state: 'unavailable', reason: 'Not downloaded' };
  assert.ok(parseUsp(UspDataPackSchema, input));
});
async function inCopy(run: (directory: string) => Promise<void>) {
  const directory = await mkdtemp(path.join(tmpdir(), 'ulpin-f0-pack-'));
  try { await cp(root, directory, { recursive: true }); await run(directory); }
  finally { await rm(directory, { recursive: true, force: true }); }
}
test('changed bytes fail integrity validation even when length is unchanged', async () => inCopy(async directory => {
  const file = path.join(directory, 'records.csv');
  const contents = await readFile(file, 'utf8'); await writeFile(file, contents.replace('000127', '999127'));
  await assert.rejects(verifyUspPack(path.join(directory, 'manifest.json')), /hash mismatch/);
}));
test('wrong declared size fails before hashing', async () => inCopy(async directory => {
  const input = await fresh(); input.assets[0].content.bytes += 1;
  await writeFile(path.join(directory, 'manifest.json'), JSON.stringify(input));
  await assert.rejects(verifyUspPack(path.join(directory, 'manifest.json')), /size\/budget mismatch/);
}));
test('symlink assets are not followed', async () => inCopy(async directory => {
  await rm(path.join(directory, 'records.csv'));
  await symlink(path.join(root, 'records.csv'), path.join(directory, 'records.csv'));
  await assert.rejects(verifyUspPack(path.join(directory, 'manifest.json')), /Symlink/);
}));
test('unavailable originals remain an explicit result, not silently fetched', async () => inCopy(async directory => {
  const input = await fresh(); input.assets[0].content = { state: 'unavailable', reason: 'Not obtained' };
  await writeFile(path.join(directory, 'manifest.json'), JSON.stringify(input));
  const result = await verifyUspPack(path.join(directory, 'manifest.json'));
  assert.equal(result.checked.length, 2); assert.equal(result.unavailable.length, 1);
}));

function acquisitionFor(asset: any) {
  return {
    schemaVersion: 'usp-pack-provenance/1', sourceFamily: 'authored-contract-smoke', sourceRelease: null,
    resourceId: null, nativeIds: ['000127'], acquiredAt: '2026-09-25T00:00:00Z',
    original: { sha256: asset.content.sha256, bytes: asset.content.bytes },
    parser: { name: 'literal CSV', version: null }, heightType: null, benchmark: null, coverage: null,
    licenceFamily: null, trainingPermission: { state: 'unconfirmed', reason: 'Not assessed' },
    purpose: 'authored_demo', privacy: 'authored non-personal fixture', subsetLineage: [], missingCapabilities: ['survey_accuracy'],
    stages: { discovered: pass, acquired: pass, inspected: { status: 'not_run' },
      qualified: { status: 'not_run' }, tested: { status: 'not_run' } }, qualificationScope: null,
  };
}

test('version-one manifests preserve optional provenance without upgrading unknowns or permission', async () => inCopy(async directory => {
  const input = await fresh(); input.assets[0].provenance = acquisitionFor(input.assets[0]);
  const parsed = parseUsp(UspDataPackSchema, input);
  assert.deepEqual(JSON.parse(JSON.stringify(parsed)), input);
  assert.equal(parsed.assets[0].provenance?.licenceFamily, null);
  assert.equal(parsed.assets[0].provenance?.benchmark, null);
  assert.equal(parsed.assets[0].provenance?.nativeIds[0], '000127');
  assert.equal(parsed.assets[0].provenance?.trainingPermission.state, 'unconfirmed');
  assert.equal(parsed.assets[1].provenance, undefined, 'legacy provenance stays absent');
  const file = path.join(directory, 'manifest.json'); await writeFile(file, JSON.stringify(input));
  const before = await readFile(file, 'utf8'); const result = await verifyUspPack(file);
  assert.equal(result.checked.length, 3);
  assert.equal(await readFile(file, 'utf8'), before, 'byte verification never promotes acquisition/permission');
}));

test('data discovery cannot qualify unacquired bytes or skip acquisition prerequisites', async () => {
  for (const change of [
    (p: any) => { p.original = null; },
    (p: any) => { p.acquiredAt = null; },
    (p: any) => { p.stages.acquired = { status: 'not_run' }; },
    (p: any) => { p.stages.discovered = { status: 'not_run' }; },
    (p: any) => { p.stages.tested = pass; p.qualificationScope = 'CSV parsing'; },
    (p: any) => { p.stages.inspected = pass; p.stages.qualified = pass; },
  ]) {
    const input = await fresh(); input.assets[0].provenance = acquisitionFor(input.assets[0]);
    change(input.assets[0].provenance); invalid(input);
  }
});

test('bounded source testing does not grant ML permission or assert measured heights', async () => {
  const input = await fresh(); const p = acquisitionFor(input.assets[0]);
  p.stages = { discovered: pass, acquired: pass, inspected: pass, qualified: pass, tested: pass };
  input.assets[0].provenance = { ...p, qualificationScope: 'Literal-code parsing only' };
  const parsed = parseUsp(UspDataPackSchema, input);
  assert.equal(parsed.assets[0].provenance?.trainingPermission.state, 'unconfirmed');
  assert.equal(parsed.assets[0].reference.verticalReference, null);
  input.assets[0].provenance.trainingPermission = { state: 'documented' }; invalid(input);
});

test('subset lineage must identify the pinned original rather than a different source', async () => {
  const input = await fresh(); input.assets[0].provenance = acquisitionFor(input.assets[0]);
  const p = input.assets[0].provenance; p.original = { sha256: 'a'.repeat(64), bytes: 100000 };
  invalid(input);
  p.subsetLineage = [{ sourceSha256: 'b'.repeat(64), operation: 'clip', evidenceRef: 'clip-receipt' }]; invalid(input);
  p.subsetLineage[0].sourceSha256 = 'a'.repeat(64);
  assert.ok(parseUsp(UspDataPackSchema, input));
});

test('authored assets cannot be relabelled as operational Indian observations', async () => {
  const input = await fresh(); input.assets[0].provenance = acquisitionFor(input.assets[0]);
  input.assets[0].provenance.purpose = 'operational_india'; invalid(input);
});

test('acquisition outside Git can retain pins while local source bytes remain unavailable', async () => {
  const input = await fresh(); input.packId = 'D5'; const asset = input.assets[0];
  asset.provenance = acquisitionFor(asset); asset.provenance.purpose = 'test_only';
  asset.origin = { kind: 'external', url: 'https://example.invalid/retained-plan' };
  asset.content = { state: 'unavailable', reason: 'Restricted original retained outside Git' };
  asset.permission = { state: 'unconfirmed', reason: 'Download does not establish redistribution or training permission' };
  const parsed = parseUsp(UspDataPackSchema, input);
  assert.equal(parsed.assets[0].content.state, 'unavailable');
  assert.equal(parsed.assets[0].provenance?.stages.acquired.status, 'passed');
  assert.equal(parsed.assets[0].verification.parsed.status, 'not_run');
});
