import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {launchBrowser} from '../../scripts/spatial/browser-launch.mjs';
const out='docs/evidence/t071',base='http://127.0.0.1:3012/';await mkdir(out,{recursive:true});
const browser=await launchBrowser(),page=await browser.newPage({viewport:{width:1440,height:1000}}),report={checks:[],errors:[],liveAppRequests:[]};page.setDefaultTimeout(15000);
page.on('pageerror',e=>report.errors.push(e.message));page.on('request',r=>{if(r.url().includes(':3000/'))report.liveAppRequests.push(r.url());});
const pass=s=>{report.checks.push(s);console.log('PASS '+s);};const go=async h=>{await page.goto(base+'#'+h);await page.locator(`#main[data-route="${h.split('/')[0]}"]`).waitFor();};const shot=async name=>page.screenshot({path:`${out}/${name}.png`,fullPage:true});
try{
 await go('batches');await page.getByRole('heading',{name:'Survey batches',exact:true}).waitFor();assert.equal(await page.locator('tbody tr').count(),3);await shot('01-batches');pass('Batch directory has fixture-derived counts and parent dependency');
 await page.getByRole('link',{name:'+ Import a batch'}).click();await page.getByRole('heading',{name:'Import a survey batch'}).waitFor();assert.equal(await page.locator('.source-row').count(),7);await shot('02-import');await page.getByRole('button',{name:'Preview sample batch'}).click();await page.getByRole('heading',{name:'Review what arrived'}).waitFor();assert.equal(await page.getByText('Metadata only',{exact:true}).count(),4);await shot('03-source-matching');pass('Seven source entries distinguish three embedded sources from four descriptors');
 await page.getByRole('link',{name:'Review exception →',exact:true}).click();await page.getByRole('heading',{name:'Review the exception'}).waitFor();await shot('04-exception-review');await page.getByRole('button',{name:'Defer and review ready records'}).click();await page.getByRole('heading',{name:'Check the recording scope'}).waitFor();assert.equal(await page.locator('#selection-count').textContent(),'26');assert(await page.locator('[data-record-object="B12"]').isDisabled());assert(!(await page.locator('[data-record-object="B12"]').isChecked()));pass('Deferral retains unresolved B12 and excludes it from recording');
 await page.locator('[data-record-object="P01"]').uncheck();assert(!(await page.locator('[data-record-object="B01"]').isChecked()));await page.locator('[data-record-object="B01"]').check();assert(await page.locator('[data-record-object="P01"]').isChecked());await page.locator('#record-ack').check();await page.locator('[data-record-object="R01"]').uncheck();assert(!(await page.locator('#record-ack').isChecked()));assert(await page.locator('#record-now').isDisabled());await page.locator('[data-record-object="R01"]').check();await shot('05-record-scope');pass('Scope includes parents, cascades exclusions and invalidates previous acknowledgement');
 await page.locator('#record-ack').check();await page.locator('#record-now').click();await page.getByRole('heading',{name:'26 objects recorded in this prototype'}).waitFor();await shot('06-recorded');await page.getByRole('link',{name:'Back to batches'}).click();await page.getByRole('heading',{name:'Survey batches',exact:true}).waitFor();assert(await page.getByText('Partly recorded',{exact:true}).isVisible());assert(await page.getByText('26 recorded · 0 ready · 1 blocked',{exact:true}).isVisible());pass('Partial recording shows progress, preserves exception and unlocks dependent floor batch');
 await go('record/BATCH-02');assert.equal(await page.locator('#selection-count').textContent(),'16');await page.locator('[data-record-object="B01-F1"]').uncheck();assert(!(await page.locator('[data-record-object="B01-F1-U1"]').isChecked()));await page.locator('[data-record-object="B01-F1-U1"]').check();assert(await page.locator('[data-record-object="B01-F1"]').isChecked());pass('Floor/space scope preserves containment dependencies');
 await go('review/plan');await page.getByRole('heading',{name:'Review the floor layout'}).waitFor();await page.locator('[data-plan-floor="2"]').click();await page.locator('[data-plan-unit="B01-F2-U2"]').click();await page.locator('#plan-overlay').uncheck();assert(await page.locator('.plan-evidence').evaluate(el=>el.classList.contains('outline-only')));await page.locator('#plan-overlay').check();await shot('18-plan-review');pass('Floor-layout review switches floors, selected spaces and proposed overlay');
 await go('register');await page.getByRole('heading',{name:'Property register',exact:true}).waitFor();await page.getByRole('searchbox',{name:'Find a property in the register'}).fill('Neem Court');assert.equal(await page.locator('tbody tr').count(),1);await page.getByRole('link',{name:'Open register →'}).click();await page.getByRole('heading',{name:'Neem Court',exact:true}).waitFor();await page.locator('[data-floor="2"]').click();assert(await page.getByText('Apartment 201',{exact:true}).first().isVisible());await shot('07-property-register');pass('Register directory searches records and opens source-linked floor/space geometry');
 await page.getByRole('tab',{name:'Rights & links'}).click();await page.getByRole('button',{name:'Inspect scope & evidence'}).click();assert(await page.getByRole('heading',{name:'Shared access',exact:true}).isVisible());assert(await page.getByText('Not established',{exact:true}).isVisible());await page.getByRole('button',{name:'Close right details'}).click();await shot('08-rights');await page.getByRole('tab',{name:'Evidence'}).click();await page.getByRole('button',{name:'Inspect source record'}).first().click();assert(await page.getByText('Height (metres)',{exact:true}).isVisible());assert(!(await page.locator('#source-dialog details').getAttribute('open')));await shot('09-evidence');await page.getByRole('button',{name:'Close source record'}).click();pass('Rights are separate unverified assertions; evidence opens readable facts with optional raw record');
 await go('register/B01');const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download record'}).click();const dl=await downloadPromise;assert.equal(dl.suggestedFilename(),'B01-fictional-record.json');pass('Scoped fictional register export downloads');
 await go('map');await page.locator('.bm-canvas canvas').waitFor();await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>window.prototypeViewer.getState().selectedId),'B01');await shot('10-map');await page.locator('[data-mode="2d"]').click();assert.equal(await page.evaluate(()=>window.prototypeViewer.getState().mode),'2d');await shot('11-map-2d');await page.locator('[data-mode="3d"]').click();await page.locator('#bm-floor').selectOption('B01-F1');await page.locator('[data-floor-mode="isolate"]').click();await page.locator('#bm-space').selectOption('B01-F1-U1');assert.equal(await page.evaluate(()=>window.prototypeViewer.getState().space),'B01-F1-U1');await page.locator('[data-action="focus"]').click();await page.waitForTimeout(300);await shot('12-map-floor');pass('Map 2D/3D, floor isolation and exact unit selection work');
 await page.locator('[data-action=register]').click();await page.locator('#main[data-route=register]').waitFor();await page.getByRole('link',{name:'Locate on map ↗',exact:true}).click();await page.locator('#main[data-route=map]').waitFor();assert.equal(await page.evaluate(()=>window.prototypeViewer.getState().space),'B01-F1-U1');await page.locator('[data-action=close-inspector]').click();assert.equal(await page.evaluate(()=>window.prototypeViewer.getState().inspectorOpen),false);await page.locator('[data-action=properties]').click();assert.equal(await page.evaluate(()=>window.prototypeViewer.getState().inspectorOpen),true);await page.locator('.bm-property-pop [data-action=close-pop]').click();pass('Map context survives register navigation and inspector can close/reopen');
 await page.locator('[data-control="explode"]').click();assert(await page.evaluate(()=>window.prototypeViewer.getState().explode));await page.locator('[data-control="explode"]').click();await page.locator('[data-control="section"]').click();await page.locator('#bm-cut').fill('5.2');await page.locator('#bm-cut').dispatchEvent('input');assert(await page.evaluate(()=>window.prototypeViewer.getState().section));await shot('13-map-section');await page.locator('[data-control="section"]').click();await page.locator('[data-action="underground"]').click();assert(await page.evaluate(()=>window.prototypeViewer.getState().underground));await shot('14-map-underground');pass('Floor separation, section plane and underground controls change map state');
 await page.locator('[data-action="layers"]').click();await page.locator('[data-layer="parcels"]').uncheck();assert(!(await page.evaluate(()=>window.prototypeViewer.getState().layers.parcels)));await page.locator('[data-layer="parcels"]').check();await page.locator('[data-action="properties"]').click();await page.locator('.bm-search input').fill('Unmeasured');await page.locator('[data-select="B12"]').click();assert.equal(await page.evaluate(()=>window.prototypeViewer.getState().selectedId),'B12');await shot('15-map-unknown-height');assert((await page.locator('.bm-inspector').innerText()).match(/height|footprint/i));pass('Layers and property search work; unknown-height property remains explicit');
 await page.setViewportSize({width:900,height:900});await go('map');await page.locator('.bm-canvas canvas').waitFor();await page.waitForTimeout(200);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot('16-tablet-map');await go('record/BATCH-01');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot('17-tablet-record');pass('Tablet map and scope layouts have no horizontal overflow');
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.liveAppRequests,[]);pass('No page errors or requests to the live application');report.result='PASS';
}catch(e){report.result='FAIL';report.error=e.stack;console.error(e.stack);await page.screenshot({path:out+'/failure.png',fullPage:true});process.exitCode=1;}finally{await writeFile(out+'/verification.json',JSON.stringify(report,null,2));await browser.close();}
