import { useLayoutEffect, useState } from 'react';
import { X, FileText, Download, Layers3, Users, Map, ArrowUpRight, Landmark, Info, ChevronDown, Search, Mouse, Move, Rotate3D, Scroll, TriangleAlert, History, ShieldCheck } from 'lucide-react';
import type { Building, Finding, ModalKind, Unit, RecordContext } from '../types';
import { useDialog } from './useDialog';
import RegisterOverview from './RegisterOverview';
import PreparedDocumentViewer from './PreparedDocumentViewer';
import { district } from '../data/district';
import { documentFields, documentTitles, downloadDocument, money } from '../data/documents';
import type { DocumentType } from '../data/documents';
import { BuildingPreview, FloorPlan, AerialMap } from './Visuals';
type Props={kind:ModalKind;building:Building;findings:Finding[];onClose:()=>void;onFloor:(f:number|null)=>void;context?:RecordContext;onContext?:(context:RecordContext)=>void;preview?:string};
export default function RecordModal({kind,building:b,findings,onClose,onFloor,context={},onContext,preview}:Props){
  const initialUnit=b.units.find(u=>u.id===context.unitId)||b.units.find(u=>u.floor===context.floor)||b.units.find(u=>u.tenure==='Rented')||b.units[0];
  const [docType,setDocType]=useState<DocumentType>(context.doc||'land'),[unit,setUnit]=useState<Unit>(initialUnit),[floor,setFloor]=useState(context.floor??initialUnit.floor),[showDoc,setShowDoc]=useState(kind==='documents'||Boolean(context.doc));
  const [registerTab,setRegisterTab]=useState<'overview'|'floors'|'evidence'|'issues'|'history'|'investigation'>('overview');
  const dialogRef=useDialog(onClose);
  useLayoutEffect(()=>{const selected=b.units.find(u=>u.id===context.unitId)||b.units.find(u=>u.floor===context.floor)||b.units.find(u=>u.tenure==='Rented')||b.units[0];setUnit(selected);setFloor(context.floor??selected.floor);setDocType(context.doc??'land');setShowDoc(kind==='documents'||Boolean(context.doc));},[context.unitId,context.floor,context.doc,kind,b]);

  const title=kind==='register'?'Building register':kind==='aerial'?'District aerial overview':kind==='help'?'Explore the district':'Evidence & documents';
  const openDocument=(type:DocumentType,u?:Unit)=>{setDocType(type);if(u){setUnit(u);setFloor(u.floor);}setShowDoc(true);onContext?.({doc:type,unitId:(u??unit).id,floor:(u??unit).floor});};
  return <div className={`rec-backdrop ${kind==='register'?'register-workspace':''}`} onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section ref={dialogRef} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="record-title" className={`rec-modal ${kind==='aerial'?'rec-aerial-modal':''}`}>
    <header className="rec-header"><div><span className="rec-header-icon">{kind==='aerial'?<Map size={21}/>:<FileText size={21}/>}</span><div><h2 id="record-title">{title}</h2><p>{b.ulpin} <span> / </span> {b.name}</p></div></div><div><span className="demo-label">SYNTHETIC DEMO</span>{kind==='register'&&<button className="back-to-map" onClick={onClose}>Back to map <ArrowUpRight size={14}/></button>}<button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={22}/></button></div></header>
    <div className="rec-body">
      {kind==='help'?<div className="rec-help"><h2>A whole neighbourhood, connected.</h2><p>Explore {district.buildings.length} buildings, their parcels, floors, residents and inspection evidence. The bundled scene needs no map API key. New uploads use the existing project backend.</p><div className="rec-help-grid">{[[Move,'Pan','Drag with the left mouse button.'],[Rotate3D,'Orbit & tilt','Drag with the right mouse button.'],[Mouse,'Zoom','Scroll in and out, or use + / −.'],[Search,'Find a property','Search its 14-digit demo ULPIN, owner or address.'],[Layers3,'Inspect floors','Select a building, then choose Floors or Explode.'],[Map,'See the entire area','Use Fit district. Click the minimap to jump to a building.']].map(([Icon,t,d])=>{const I=Icon as typeof Move;return <div key={String(t)}><I size={23}/><h3>{String(t)}</h3><p>{String(d)}</p></div>;})}</div><div className="rec-disclaimer"><Info size={18}/><p>Buildings, parcels, identifiers, residents and documents are generated fixtures, not official or surveyed records. The visual style follows the supplied mockups; this is not photogrammetry. Underground pipe sizes are exaggerated for visibility; elevation values remain in local metres.</p></div></div>:
      kind==='aerial'?<div className="rec-aerial-layout"><div className="rec-aerial-map"><AerialMap selected={b.id}/></div><aside><span className="ins-eyebrow">ORTHOGRAPHIC DISTRICT SHEET</span><h2>Lake View District</h2><p>The complete district, generated from the same parcel and building geometry as the 3D map.</p><div className="rec-aerial-stats"><strong>{district.buildings.length}<small>Buildings</small></strong><strong>{(district.extent**2/1e6).toFixed(3)}<small>km² local extent</small></strong><strong>{district.parks.length}<small>Public parks</small></strong></div><p className="rec-legend"><i style={{background:'#dc745b'}}/>Selected building<br/><i style={{background:'#efe6d2'}}/>Modelled buildings<br/><i style={{background:'#88a16b'}}/>Public land<br/><i style={{background:'#7e8980'}}/>Road corridors</p><button className="primary-button" onClick={()=>downloadDocument('aerial',b)}><Download size={16}/>Download overview PDF</button><div className="rec-disclaimer"><Info size={17}/><p>This is a synthetic aerial-style diagram, not a drone or satellite photograph. North is at the top; local extent is {district.extent} × {district.extent} m.</p></div></aside></div>:
      <div className="rec-layout"><aside className="rec-property">{preview?<img className="building-preview" src={preview} alt={b.name}/>:<BuildingPreview b={b}/>}<h3>{b.name}</h3><code>{b.ulpin}</code><p>{b.address}</p><div className="rec-property-stats"><span>{b.floors}<small>Floors</small></span><span>{b.units.length}<small>Units</small></span><span>{b.height.toFixed(1)}<small>Height, m</small></span></div><div className="rec-owner"><Landmark size={17}/><div><small>Recorded owner · fictional</small><strong>{b.owner}</strong></div></div><button onClick={()=>{setShowDoc(false);onContext?.({unitId:unit.id,floor:unit.floor});}} className={!showDoc&&kind==='register'?'active':''}><Layers3 size={15}/>Floor & occupancy schedule</button><button onClick={()=>openDocument('land')}><Landmark size={15}/>Land & parcel record</button><button onClick={()=>openDocument('plan')}><Map size={15}/>Illustrative floor plan</button><button onClick={()=>openDocument('lease')}><Users size={15}/>Occupancy record</button><button onClick={()=>downloadDocument('register',b)}><Download size={15}/>Download complete register</button><div className="ins-note">All linked people and evidence are fictional. Documents carry a visible demo disclaimer.</div></aside>
      <main className="rec-main">
        {kind==='register'&&!showDoc&&<nav className="register-full-tabs" aria-label="Full register sections">{([['overview','Overview'],['floors','Floors & units'],['evidence','Evidence'],['issues','Issues'],['history','History'],['investigation','Investigation']] as const).map(([id,label])=><button key={id} className={registerTab===id?'active':''} aria-current={registerTab===id?'page':undefined} onClick={()=>setRegisterTab(id)}>{label}</button>)}</nav>}
        {!showDoc&&kind==='register'&&registerTab==='overview'?<RegisterOverview b={b} unit={unit} floor={floor} onFloor={f=>{const u=unit.floor===f?unit:b.units.find(u=>u.floor===f)!;setFloor(f);setUnit(u);onContext?.({unitId:u.id,floor:f});}} onUnit={u=>{setUnit(u);setFloor(u.floor);onContext?.({unitId:u.id,floor:u.floor});}} onDocument={u=>openDocument('lease',u)} onMap={onFloor}/>:
        !showDoc&&kind==='register'&&registerTab==='floors'?<div className="register-full-panel"><div className="rec-section-heading"><div><span className="ins-eyebrow">COMPLETE SCHEDULE</span><h2>Floors & units</h2></div><span>{b.units.length} linked unit records</span></div><RegisterOverview b={b} unit={unit} floor={floor} onFloor={f=>{const u=b.units.find(u=>u.floor===f)!;setFloor(f);setUnit(u);}} onUnit={u=>{setUnit(u);setFloor(u.floor);}} onDocument={u=>openDocument('lease',u)} onMap={onFloor}/></div>:
        !showDoc&&kind==='register'&&registerTab==='evidence'?<div className="register-full-panel"><div className="rec-section-heading"><div><span className="ins-eyebrow">RETAINED EVIDENCE</span><h2>Evidence & documents</h2></div></div><div className="register-evidence-grid"><button onClick={()=>openDocument('land')}><Landmark size={22}/><strong>Land & parcel record</strong><span>{b.parcelId}</span></button><button onClick={()=>openDocument('plan')}><Layers3 size={22}/><strong>Floor plans</strong><span>{b.floors} prepared floor records</span></button><button onClick={()=>openDocument('lease',unit)}><FileText size={22}/><strong>Occupancy records</strong><span>{b.units.length} unit-linked records</span></button><button onClick={()=>downloadDocument('aerial',b)}><Map size={22}/><strong>Neighbourhood overview</strong><span>Prepared source PDF</span></button></div><p className="register-boundary-note">These are synthetic prepared originals for the Studio fixture. For imported properties, use Saved registers to inspect retained source pages, revisions and locators.</p><a className="register-external-link" href="/register">Open saved property registers <ArrowUpRight size={15}/></a></div>:
        !showDoc&&kind==='register'&&registerTab==='issues'?<div className="register-full-panel"><div className="rec-section-heading"><div><span className="ins-eyebrow">COMPUTED REVIEW</span><h2>Issues & discrepancies</h2></div><span>{findings.length} findings</span></div>{findings.length?findings.map(f=><article className="register-full-issue" key={f.id}><TriangleAlert size={20}/><div><strong>{f.title}</strong><p>{f.description}</p><small>{f.type} · computed from this fixture</small></div><b>{f.value} {f.unit}</b></article>):<p className="register-empty-findings">No computed geometry findings.</p>}<p className="register-boundary-note">Findings are technical demo checks, not legal determinations.</p></div>:
        !showDoc&&kind==='register'&&registerTab==='history'?<div className="register-full-panel"><div className="rec-section-heading"><div><span className="ins-eyebrow">PROVENANCE</span><h2>Record history</h2></div></div><ol className="register-full-history"><li><History size={18}/><div><strong>Land record fixture retained</strong><span>{b.registeredOn}</span><p>Prepared synthetic source linked to {b.parcelId}.</p></div></li><li><Users size={18}/><div><strong>Unit records prepared</strong><span>2026 fixture</span><p>{b.units.length} fictional occupancy records linked to exact floors.</p></div></li><li><ShieldCheck size={18}/><div><strong>Geometry checks computed</strong><span>Current source revision</span><p>{findings.length} current findings. Historical geometry playback is not claimed for this authored fixture.</p></div></li></ol><a className="register-external-link" href="/register">Open saved registers with retained revision history <ArrowUpRight size={15}/></a></div>:
        !showDoc&&kind==='register'&&registerTab==='investigation'?<div className="register-full-panel"><div className="rec-section-heading"><div><span className="ins-eyebrow">TECHNICAL REVIEW</span><h2>Investigation</h2></div></div><div className="register-investigation-empty"><Search size={30}/><h3>No persisted case for this synthetic fixture</h3><p>The Studio example has computed findings but no fabricated investigation lifecycle. Persisted properties support evidence requests, decisions and case exports in the saved register.</p><a href="/register">Open saved registers <ArrowUpRight size={15}/></a></div></div>:
        !showDoc?<RegisterOverview b={b} unit={unit} floor={floor} onFloor={f=>{const u=unit.floor===f?unit:b.units.find(u=>u.floor===f)!;setFloor(f);setUnit(u);onContext?.({unitId:u.id,floor:f});}} onUnit={u=>{setUnit(u);setFloor(u.floor);onContext?.({unitId:u.id,floor:u.floor});}} onDocument={u=>openDocument('lease',u)} onMap={onFloor}/>:<>

          <div className="rec-doc-tabs">{(['land','plan','lease'] as DocumentType[]).map(t=><button key={t} onClick={()=>openDocument(t)} className={docType===t?'active':''}>{t==='land'?'Land record':t==='plan'?'Floor plan':'Occupancy record'}</button>)}</div>
          <div className="rec-section-heading"><div><span className="ins-eyebrow">INSPECTION SPECIMEN</span><h2>{documentTitles[docType]}</h2></div><button className="primary-button" onClick={()=>downloadDocument(docType,b,unit,floor)}><Download size={15}/>PDF</button></div>
          {docType==='plan'&&<div className="rec-doc-control"><label>Floor<select aria-label="Floor" value={floor} onChange={e=>{const f=Number(e.target.value),u=b.units.find(u=>u.floor===f)!;setFloor(f);setUnit(u);onContext?.({doc:docType,unitId:u.id,floor:f});}}>{Array.from({length:b.floors},(_,f)=><option key={f} value={f}>{f===0?'Ground floor':`Floor ${f}`}</option>)}</select></label></div>}
          {docType==='lease'&&<div className="rec-doc-control"><label>Unit / occupant<select aria-label="Unit and occupant" value={unit.id} onChange={e=>{const u=b.units.find(u=>u.id===e.target.value)!;setUnit(u);setFloor(u.floor);onContext?.({doc:docType,unitId:u.id,floor:u.floor});}}>{b.units.map(u=><option key={u.id} value={u.id}>Unit {u.number} · {u.occupant}</option>)}</select></label></div>}
          <div className="rec-document original-not-facsimile"><PreparedDocumentViewer buildingId={b.id} kind={docType} unitId={unit.id} floor={floor}/><details className="record-linked-fields"><summary>Linked record fields</summary><dl className="rec-doc-fields">{documentFields(docType,b,unit,floor).map(([l,v])=><div key={l}><dt>{l}</dt><dd>{v}</dd></div>)}</dl></details></div>

        </>}
      </main>{kind==='register'&&!showDoc&&<aside className="register-evidence">
        <section><header><h3>Evidence & documents</h3><span>Demo records</span></header>
          <button onClick={()=>openDocument('land')}><Landmark size={20}/><div><strong>Land & parcel record</strong><small>{b.parcelId}</small></div><ArrowUpRight size={13}/></button>
          <button onClick={()=>openDocument('plan')}><Layers3 size={20}/><div><strong>Floor plans</strong><small>G through floor {b.floors-1} · metre-based</small></div><ArrowUpRight size={13}/></button>
          <button onClick={()=>openDocument('lease',unit)}><FileText size={20}/><div><strong>Occupancy record</strong><small>Selected unit {unit.number}</small></div><ArrowUpRight size={13}/></button>
          <button onClick={()=>downloadDocument('aerial',b)}><Map size={20}/><div><strong>District overview</strong><small>Download the full-area PDF</small></div><Download size={13}/></button>
        </section>
        <section><header><h3>Issues & discrepancies</h3><span>{findings.length} findings</span></header>{findings.length?findings.map(f=><div className="register-issue" key={f.id}><div><strong>{f.title}</strong><b>{f.value} {f.unit}</b></div><p>{f.description}</p></div>):<p className="register-empty-findings">No geometry findings for this demo footprint.</p>}</section>
        <section><header><h3>Fixture provenance</h3></header><div className="register-history"><p><i/>Land record fixture<span>{b.registeredOn}</span></p><p><i/>Occupancy period begins<span>2026-04-01</span></p><p><i/>Geometry checks<span>Computed in this session</span></p></div><p className="ins-note">These are synthetic record dates, not a real approval or ownership history.</p></section>
      </aside>}</div>}
    </div>
  </section></div>;
}
