import {mountMap,deriveSpatialChecks} from './shared/runtime.js';
import {normalizeReferencePackage} from './shared/contract.js';
async function readPackage(file){const result=await normalizeReferencePackage(file.name,new Uint8Array(await file.arrayBuffer()));window.prototypeCanonical=result.canonical;return {data:result.render.scene,verifiedFiles:result.receipt.verifiedFiles,name:file.name,receipt:result.receipt};}
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data,pending,viewer,currentReceipt,receiptUrl;
const counts=d=>['building','parcel','floor','space'].map(type=>({type,n:d.objects.filter(o=>o.type===type).length}));
const countHTML=d=>`<div class="counts">${counts(d).map(c=>`<div><strong>${c.n}</strong><span>${c.type==='space'?'spaces':c.type+'s'}</span></div>`).join('')}</div>`;
function record(id,review=false){const o=data.objects.find(o=>o.id===id);if(!o)return;const g=data.geometries.find(g=>g.id===o.geometryId),sources=(o.sourceRecordIds||[]).map(id=>data.sourceRecords.find(r=>r.id===id)).filter(Boolean),issues=(data.issues||[]).filter(i=>i.objectId===id||i.targetId===id||i.objectIds?.includes(id));$('#record-body').innerHTML=`<p class="eyebrow">${esc(o.type)} · ${esc(o.id)}</p><h2>${esc(o.label)}</h2><dl class="record-fields"><dt>Internal 3D identity</dt><dd>${esc(o.systemId)}</dd><dt>Official ULPIN</dt><dd>Not issued · fictional property</dd><dt>Geometry</dt><dd>${g?esc(g.type)+' · '+esc(g.version):'Unavailable'}</dd><dt>Height</dt><dd>${g?.heightM==null?'Unknown':esc(g.heightM)+' m'}</dd><dt>Frame</dt><dd>${esc(g?.frameId)}</dd><dt>Vertical benchmark</dt><dd>${esc(g?.verticalDatum)}</dd></dl>${issues.length?`<div class="warning">${issues.map(i=>`<div style="margin-bottom:12px"><strong>${esc(i.title||i.message||i.code)}</strong>${Number.isFinite(i.evidence?.areaM2)?`<p>${esc(i.evidence.areaM2.toFixed(2))} m² · ${esc((i.objectIds||[]).join(' / '))}</p>`:''}${Number.isFinite(i.evidence?.volumeM3)?`<p>Overlapping volume: ${esc(i.evidence.volumeM3.toFixed(2))} m³</p>`:''}<p>${esc(i.description||'')}</p></div>`).join('')}Review the source boundaries and geometry before resolving these findings.</div>`:''}<h3>Linked source records</h3>${sources.map(s=>`<div class="source"><strong>${esc(s.sourceId)} · ${esc(s.recordKey)}</strong><span>${esc(s.locator)}</span></div>`).join('')||'<p>No source records attached.</p>'}<details><summary>Original attributes and geometry</summary><pre>${esc(JSON.stringify({object:o,geometry:g,sourceRecords:sources},null,2))}</pre></details>${review?'<p class="note">This is an evidence preview. Review decisions and publication belong to the application workflow.</p>':''}`;$('#record-dialog').showModal()}
function mount(next,receipt){const old=data;try{if(next.canonicalSchemaVersion!=='ulpin-spatial/2')throw new Error('The map requires a validated canonical projection.');const checked=deriveSpatialChecks(next);viewer?.dispose();data=checked;viewer=mountMap($('#map'),data,{onRegister:id=>record(id),onReview:id=>record(id,true),onWorkspace:id=>record(id,true)});if(receipt){currentReceipt=receipt;if(receiptUrl)URL.revokeObjectURL(receiptUrl);receiptUrl=URL.createObjectURL(new Blob([receipt.originalBytes]));const link=$('#data-dialog a[download]');link.href=receiptUrl;link.download=receipt.name;}window.prototypeData=data;window.prototypeViewer=viewer;const cs=counts(data);$('#scene-count').textContent=`${cs[0].n} buildings`;$('#scene-summary').textContent=`${data.spatialCheckReport?.issueCount||0} spatial findings ↗`;$('#scene-summary').disabled=false;$('.context .eyebrow').textContent=data.metadata.title.replace(/ ·.*/,'').toUpperCase();$('#data-summary').innerHTML=countHTML(data);$('#source-list').innerHTML=`<div class="source"><strong>${esc(data.frames[0]?.name)}</strong><span>${esc(data.frames[0]?.verticalDatum)}</span></div>`+(data.sources||[]).map(s=>`<div class="source"><strong>${esc(s.label||s.id)}</strong><span>${esc(s.modality)} · ${esc(s.classification)} · revision ${esc(s.revision)}</span></div>`).join('');}catch(e){if(old&&old!==next)mount(old);throw e}}
$('#scene-summary').onclick=()=>{const issues=data.issues.filter(i=>i.origin==='spatial-preview');$('#findings-list').innerHTML=issues.length?issues.map(i=>`<article class="finding-card"><div><strong>${esc(i.title)}</strong><span class="finding-area">${Number.isFinite(i.evidence?.areaM2)?esc(i.evidence.areaM2.toFixed(2))+' m²':''}</span></div><p>${esc(i.description)}</p><div class="finding-actions">${(i.objectIds||[]).filter(id=>data.objects.some(o=>o.id===id&&o.type==='building')).map(id=>`<button class="button" data-find-building="${esc(id)}">Inspect ${esc(id)} ↗</button>`).join('')}</div></article>`).join(''):'<p class="note">No positive-area findings in the checked geometry. Missing or unmeasurable records are reported separately.</p>';if(data.spatialCheckReport?.status!=='complete')$('#findings-list').insertAdjacentHTML('afterbegin','<p class="warning">Some comparisons could not be measured because geometry or reference information is unavailable. This is not a complete clear result.</p>');for(const b of document.querySelectorAll('[data-find-building]'))b.onclick=()=>{viewer.select(b.dataset.findBuilding);$('#findings-dialog').close()};$('#findings-dialog').showModal();};
for(const [button,dialog] of [['data-button','data-dialog'],['import-button','import-dialog'],['help-button','help-dialog']])$('#'+button).onclick=()=>$('#'+dialog).showModal();
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>b.closest('dialog').close();
for(const d of document.querySelectorAll('dialog'))d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});
$('#dataset-file').onchange=async e=>{pending=null;$('#apply-import').disabled=true;$('#import-preview').hidden=true;const status=$('#import-status');status.className='';const file=e.target.files[0];if(!file)return;status.textContent='Reading files and checking geometry links…';try{pending=await readPackage(file);pending.data=deriveSpatialChecks(pending.data);status.textContent=pending.verifiedFiles?`${pending.verifiedFiles} file hashes verified. Geometry, frames and record links checked.`:'Geometry, frames and record links checked. No package hashes were supplied.';const report=pending.data.spatialCheckReport;status.textContent+=report?.status==='complete'?` ${report.issueCount} spatial findings computed from the geometry.`:` Spatial checks ${report?.status||'unavailable'}; some comparisons could not be measured.`;$('#import-preview').innerHTML=countHTML(pending.data);$('#import-preview').hidden=false;$('#apply-import').disabled=false}catch(error){status.className='error';status.textContent=error.message}};
$('#apply-import').onclick=()=>{if(!pending)return;try{mount(pending.data,pending.receipt);$('#import-dialog').close();$('.toast').textContent=`Opened ${pending.name} in this preview.`;$('.toast').hidden=false;setTimeout(()=>$('.toast').hidden=true,3500)}catch(error){$('#import-status').className='error';$('#import-status').textContent=error.message}};
try{const response=await fetch('./data/neem-reference-dataset.zip');if(!response.ok)throw new Error('The demonstration dataset could not be loaded.');const result=await readPackage(new File([await response.arrayBuffer()],'neem-reference-dataset.zip'));mount(result.data,result.receipt)}catch(error){$('#map').innerHTML=`<p style="padding:30px">${esc(error.message)}</p>`;console.error(error)}

$('#check-button').onclick=()=>$('#scene-summary').click();
$('#export-button').onclick=()=>$('#data-button').click();
$('#global-search').addEventListener('keydown',e=>{if(e.key!=='Enter'||!data)return;const q=e.target.value.trim().toLowerCase();const match=data.objects.find(o=>o.type==='building'&&`${o.label} ${o.id} ${o.systemId||''}`.toLowerCase().includes(q));if(match){viewer.select(match.id);e.target.value=''}else{$('.toast').textContent='No matching property in this dataset.';$('.toast').hidden=false;setTimeout(()=>$('.toast').hidden=true,3500)}});

for(const button of document.querySelectorAll('[data-sample]'))button.onclick=async()=>{const status=$('#import-status');status.textContent='Verifying sample package…';$('#apply-import').disabled=true;try{const response=await fetch(button.dataset.sample);if(!response.ok)throw new Error('Sample package unavailable');const name=button.dataset.sample.split('/').at(-1);pending=await readPackage(new File([await response.arrayBuffer()],name));status.textContent=`${pending.data.metadata.title} · canonical contract verified`;$('#import-preview').innerHTML=countHTML(pending.data);$('#import-preview').hidden=false;$('#apply-import').disabled=false}catch(e){status.textContent=e.message}};
