import {launchBrowser} from '../../scripts/spatial/browser-launch.mjs';
import {mkdir,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';

const url=process.argv[2]||'http://127.0.0.1:3013/';
const output=process.argv[3]||'/tmp/t073-map-verification';
await mkdir(output,{recursive:true});
const browser=await launchBrowser();
const results={url,viewport:{width:1440,height:1000},errors:[],checks:[]};
const page=await browser.newPage({viewport:results.viewport,deviceScaleFactor:1});
page.on('pageerror',error=>results.errors.push(error.message));
const assert=(condition,message)=>{if(!condition)throw new Error(message);results.checks.push(message);};
const state=()=>page.evaluate(()=>window.prototypeViewer.getState());
const stats=()=>page.evaluate(()=>window.prototypeViewer.getStats());
const capture=async name=>{await page.waitForTimeout(140);await page.screenshot({path:`${output}/${name}.png`});};
const canvasHash=async()=>createHash('sha256').update(await page.locator('.bm-canvas').screenshot()).digest('hex');
try{
  await page.goto(url);await page.waitForFunction(()=>window.prototypeViewer?.getStats?.().renderCount>0);await page.waitForTimeout(500);
  await capture('01-opening');results.openingStats=await stats();const opening=await state();
  const conflicts=results.openingStats.spatialConflicts;
  assert(conflicts.length===4&&conflicts.find(c=>c.code==='ROAD_OVERLAP').areaM2===16,'Four positive-area computed findings include exact 16 m² road intrusion');
  assert((await page.locator('.bm-conflict-card').innerText()).includes('16 m²'),'Inspector explains actual computed overlap area');
  await page.locator('.bm-conflict-row').first().click();
  assert((await state()).activeConflictId===conflicts.find(c=>c.code==='OUTSIDE_PARCEL'&&c.buildingIds.includes('B01')).id,'Inspector selects an exact intersection geometry');
  await page.evaluate(()=>window.prototypeViewer.select('B02'));
  assert((await page.evaluate(()=>window.prototypeViewer.inspectObject('B01'))).visualStatus==='conflict','B01 remains red after selecting another building');
  assert((await page.evaluate(()=>window.prototypeViewer.inspectObject('B03'))).visualStatus==='conflict','Both overlapping buildings retain independent conflict states');
  await capture('11-building-overlap');
  await page.evaluate(()=>window.prototypeViewer.setMode('2d'));
  const hitPoint=await page.evaluate(async()=>{
    const THREE=await import('three'),v=window.prototypeViewer,s=v.getState(),r=document.querySelector('.bm-canvas').getBoundingClientRect(),a=r.width/r.height,h=s.camera.orthoHalfHeight;
    const c=new THREE.OrthographicCamera(-h*a,h*a,h,-h,.1,1200);c.position.fromArray(s.camera.position);c.zoom=s.camera.zoom;c.lookAt(new THREE.Vector3(...s.camera.target));c.updateProjectionMatrix();c.updateMatrixWorld();
    const issue=window.prototypeData.issues.find(i=>i.code==='BUILDING_OVERLAP'),ring=issue.evidence.intersectionGeometry.coordinates[0][0].slice(0,-1),x=ring.reduce((sum,p)=>sum+p[0],0)/ring.length,y=ring.reduce((sum,p)=>sum+p[1],0)/ring.length;
    const top=Math.max(...['B02','B03'].map(id=>v.inspectObject(id).segments.reduce((max,seg)=>Math.max(max,seg.base+seg.height),0)))+.085;
    const point=new THREE.Vector3(x,top,-y).project(c);return{x:r.left+(point.x+1)*r.width/2,y:r.top+(1-point.y)*r.height/2,issueId:issue.id};
  });
  await page.waitForTimeout(200);await page.mouse.click(hitPoint.x,hitPoint.y);
  results.intersectionPick={hitPoint,state:await state()};
  assert((await state()).activeConflictId===hitPoint.issueId,'The actual intersection polygon is selectable on the canvas');
  const firstOverlapId=(await state()).selectedId;await page.mouse.click(hitPoint.x,hitPoint.y);
  assert((await state()).selectedId!==firstOverlapId&&['B02','B03'].includes((await state()).selectedId),'Repeated canvas clicks cycle both overlapping building identities');
  await capture('12-selected-intersection');
  await page.evaluate(()=>window.prototypeViewer.select('B04'));
  assert((await page.evaluate(()=>window.prototypeViewer.inspectObject('B04'))).visualStatus==='selected','A selected non-conflicting building is green');
  await page.evaluate(saved=>window.prototypeViewer.restoreState(saved),opening);
  await page.waitForTimeout(250);const beforeIdle=(await stats()).renderCount;await page.waitForTimeout(300);assert((await stats()).renderCount===beforeIdle,'Idle map does not render continuously');
  const missing=await page.evaluate(()=>window.prototypeViewer.inspectObject('B12'));
  assert(missing.visualStatus==='height-unresolved'&&missing.conflictIds.length===0,'Missing height alone receives no conflict tint');
  assert(missing.heightM===null&&missing.segments.length===0&&missing.bounds.max[1]-missing.bounds.min[1]<.1,'B12 has only a flat footprint');
  const initialHash=await canvasHash();await page.locator('[data-mode="2d"]').click();await page.waitForTimeout(100);
  assert((await stats()).cameraType==='OrthographicCamera','2D uses OrthographicCamera');assert(await canvasHash()!==initialHash,'2D changes actual canvas');
  await page.locator('[data-action=fit]').click();await capture('02-orthographic');
  await page.evaluate(saved=>window.prototypeViewer.restoreState(saved),opening);
  await page.locator('[data-action=focus]').click();await capture('03-focal-close');
  await page.locator('#bm-floor').selectOption('B01-F1');await page.locator('[data-floor-mode=isolate]').click();await page.locator('#bm-space').selectOption('B01-F1-U1');
  assert((await state()).space==='B01-F1-U1','Space selection keeps exact space identity');
  let object=await page.evaluate(()=>window.prototypeViewer.inspectObject('B01'));
  assert(object.segments.filter(segment=>segment.visible).map(segment=>segment.id).join(',')==='B01-F1','Isolate displays the exact selected floor');
  await capture('04-floor-space');
  await page.locator('[data-floor-mode=below]').click();await page.locator('#bm-floor').selectOption('all');await page.locator('[data-control=explode]').check();
  object=await page.evaluate(()=>window.prototypeViewer.inspectObject('B01'));assert(object.segments.some(segment=>segment.positionY!==segment.base),'Separate floors changes displayed floor positions');await capture('05-separated');
  await page.locator('[data-control=explode]').uncheck();await page.locator('[data-control=section]').check();await page.locator('#bm-cut').fill('6');assert((await state()).sectionHeight===6,'Section elevation updates');await capture('06-section');
  await page.locator('[data-control=section]').uncheck();await page.locator('#bm-floor').selectOption('B01-FB');assert((await state()).underground,'Basement selection reveals underground view');await capture('07-basement');
  await page.locator('#bm-floor').selectOption('all');await page.evaluate(saved=>window.prototypeViewer.restoreState(saved),opening);await page.locator('[data-action=underground]').click();await capture('08-underground');await page.locator('[data-action=underground]').click();
  await page.locator('[data-action=properties]').click();await page.locator('.bm-search input').fill('B12');await page.locator('[data-select=B12]').click();await page.waitForTimeout(100);
  assert((await state()).selectedId==='B12'&&await page.locator('.bm-selected-label').isVisible(),'Property search focuses the missing-height footprint');assert(await page.locator('[data-control=section]').isDisabled(),'Missing height disables section controls');await capture('09-missing-height');
  await page.evaluate(saved=>window.prototypeViewer.restoreState(saved),opening);const beforeClose=await state();const width=await page.locator('.bm-stage').evaluate(element=>element.clientWidth);await page.locator('[data-action=close-inspector]').click();await page.waitForTimeout(100);
  const closedState=await state();assert(!closedState.inspectorOpen&&await page.locator('.bm-stage').evaluate(element=>element.clientWidth)>width,'Close inspector expands canvas');assert(['position','target'].every(key=>(closedState.camera[key]).every((value,index)=>Math.abs(value-beforeClose.camera[key][index])<1e-8)),'Closing inspector preserves camera');
  await page.locator('[data-action=properties]').click();assert((await state()).inspectorOpen,'Find property restores inspector');await page.locator('.bm-property-pop [data-action=close-pop]').click();
  await page.evaluate(saved=>window.prototypeViewer.restoreState(saved),opening);await page.evaluate(()=>window.prototypeViewer.resetMetrics());
  const box=await page.locator('.bm-canvas').boundingBox();await page.mouse.move(box.x+box.width*.48,box.y+box.height*.55);await page.mouse.down();
  for(let i=0;i<60;i++){await page.mouse.move(box.x+box.width*(.48+.16*Math.sin(i/35)),box.y+box.height*(.55+.035*Math.sin(i/20)));await page.waitForTimeout(16);}
  await page.mouse.up();await page.waitForTimeout(300);results.orbitStats=await stats();results.continuousOrbitStats=await page.evaluate(()=>window.prototypeViewer.measureOrbit(2200));
  const tablet=await browser.newPage({viewport:{width:1024,height:768},deviceScaleFactor:1});await tablet.goto(url);await tablet.waitForFunction(()=>window.prototypeViewer?.getStats?.().renderCount>0);await tablet.waitForTimeout(300);await tablet.screenshot({path:`output-placeholder/tablet.png`.replace('output-placeholder',output)});results.tabletStats=await tablet.evaluate(()=>window.prototypeViewer.getStats());assert(await tablet.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Tablet has no horizontal page overflow');
  results.graphics=await page.evaluate(()=>{const canvas=document.querySelector('.bm-canvas canvas'),gl=canvas.getContext('webgl2');if(!gl)return null;const ext=gl.getExtension('WEBGL_debug_renderer_info');return {vendor:ext?gl.getParameter(ext.UNMASKED_VENDOR_WEBGL):null,renderer:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):null,userAgent:navigator.userAgent};});
  const variants=await browser.newPage({viewport:{width:1024,height:768}});await variants.goto(url);await variants.waitForFunction(()=>window.prototypeViewer?.getStats?.().renderCount>0);
  results.variantChecks=await variants.evaluate(async()=>{
    const {mountMap}=await import('./map.js'),{deriveSpatialChecks}=await import('./spatial-checks.js'),source=structuredClone(window.prototypeData),ids=new Set(['B02','B03']);
    source.objects=source.objects.filter(o=>ids.has(o.id));source.geometries=source.geometries.filter(g=>ids.has(g.objectId));source.relations=[];source.issues=[];
    const original=structuredClone(source);const host=document.querySelector('.bm-root');window.prototypeViewer.dispose();let v;
    const read=data=>{v?.dispose();v=mountMap(host,deriveSpatialChecks(data),{detail:'massing'});return{conflicts:v.getStats().spatialConflicts,states:['B02','B03'].map(id=>v.inspectObject(id).visualStatus)};};
    const unknown=structuredClone(original);unknown.geometries.find(g=>g.objectId==='B03').heightM=null;const unknownResult=read(unknown);
    const disjoint=structuredClone(original);disjoint.geometries.find(g=>g.objectId==='B03').baseElevationM=60;const disjointResult=read(disjoint);
    const touch=structuredClone(original),a=touch.geometries.find(g=>g.objectId==='B02'),b=touch.geometries.find(g=>g.objectId==='B03'),dx=Math.max(...a.coordinates[0].map(p=>p[0]))-Math.min(...b.coordinates[0].map(p=>p[0]));b.coordinates.forEach(ring=>ring.forEach(p=>p[0]+=dx));const touchingResult=read(touch);v.dispose();
    return {unknown:unknownResult,disjoint:disjointResult,touching:touchingResult};
  });await variants.close();
  assert(results.variantChecks.unknown.conflicts.length===1&&!results.variantChecks.unknown.conflicts[0].solidTint&&results.variantChecks.unknown.states.every(s=>s!=='conflict'),'Unknown height shows footprint overlap without inventing a solid collision');
  assert(results.variantChecks.disjoint.conflicts.length===0,'Vertically disjoint buildings receive no collision tint');
  assert(results.variantChecks.touching.conflicts.length===0,'Shared-wall contact receives no positive-area conflict');
  const fallback=await browser.newPage({viewport:{width:1024,height:768}});
  await fallback.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){if(/webgl/i.test(type))return null;return original.call(this,type,...args);};});
  await fallback.goto(url);await fallback.waitForSelector('.bm-render-error');await fallback.locator('[data-action=properties]').click();await fallback.locator('.bm-search input').fill('B12');await fallback.locator('[data-select=B12]').click();
  assert((await fallback.locator('.bm-inspector h2').textContent()).length>0,'WebGL fallback keeps property retrieval and inspector available');await fallback.screenshot({path:`${output}/10-webgl-fallback.png`});
  assert(results.errors.length===0,'No browser page errors');
}catch(error){results.failure=error.message;process.exitCode=1;}finally{await writeFile(`${output}/results.json`,JSON.stringify(results,null,2));console.log(JSON.stringify({output,checks:results.checks.length,failure:results.failure||null,openingStats:results.openingStats,orbitStats:results.orbitStats,continuousOrbitStats:results.continuousOrbitStats,errors:results.errors}));await browser.close();}
