'use client';
import Link from 'next/link';
import {Upload,Download,Check,ArrowRight} from 'lucide-react';
import {useMemo} from 'react';
import {deriveSpatialChecks} from '../reference-runtime/spatial-checks';
import type {normalizeReferencePackage} from '../reference-import/browser';
type Imported=Awaited<ReturnType<typeof normalizeReferencePackage>>;
export function ImportReceipt({pending,busy,error,onFile,onSample,onDownload,onReset,onOpen}:{pending:Imported|null;busy:boolean;error:string;onFile:(file:File)=>void;onSample:(path:string)=>void;onDownload:()=>void;onReset:()=>void;onOpen:()=>void}){
 const result=useMemo(()=>pending?deriveSpatialChecks(pending.render.scene):null,[pending]);
 const counts=(type:string)=>pending?.render.scene.objects.filter(o=>o.type===type).length??0;
 const sources=pending?.render.scene.sources??[];
 const retained=sources.filter(s=>s.processing==='retained').length;
 return <div className="rw-import-flow">
  <ol className="rw-steps" aria-label="Import progress"><li data-done={!!pending}>{pending?<Check size={15}/>:<span>1</span>}Import files</li><li data-done={!!pending}>{pending?<Check size={15}/>:<span>2</span>}Match & build</li><li aria-current={pending?'step':undefined}><span>3</span>Review draft</li></ol>
  {!pending&&<><p>Import an area’s source package. Buildings, floors and property records are matched by their supplied IDs.</p><label className="rw-drop"><Upload size={25}/><strong>{busy?'Reading source files…':'Choose a dataset ZIP or JSON'}</strong><span>Up to 20 MB · original files are retained</span><input aria-label="Choose dataset file" type="file" accept=".zip,.json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)onFile(file);}}/></label>
  <div className="rw-demo-package"><div><strong>Lake View · complete sample</strong><p>The reference city, with plans, GIS, controls, point clouds, imagery, elevation and fictional property records.</p></div><div><button disabled={busy} onClick={onDownload}><Download size={15}/>Download ZIP</button><button disabled={busy} onClick={()=>onSample('lake-view-complete.zip')}>Try sample <ArrowRight size={15}/></button></div></div>
  <details className="rw-other-samples"><summary>Other datasets & supported formats</summary><div className="rw-samples">{[['Dense colony','showcase-dense.zip'],['Courtyard & elevated','independent-arrangements.json'],['Shiv Vihar · MASTER','provided-master.zip'],['Shiv Vihar · normalized','provided-normalized.zip']].map(([label,path])=><button key={path} disabled={busy} onClick={()=>onSample(path)}>{label}</button>)}</div><p>Supported here: declared local-metre GeoJSON/CSV packages, the supplied MASTER and normalized v1 formats, and normalized scene JSON. Binary files are retained as supporting evidence; they do not automatically produce geometry in this importer.</p><Link href="/studio/add-files">Open saved source intake for raw GIS, plans and documents →</Link></details></>}
  {busy&&<p role="status">Verifying fingerprints, matching source IDs and building the draft…</p>}{error&&<p className="rw-error" role="alert">{error}</p>}
  {pending&&<><h3 className="rw-receipt-title">Your draft is ready to inspect</h3><div className="rw-receipt-counts">{[[counts('building'),'Buildings'],[counts('floor'),'Floors'],[counts('space'),'Units / spaces'],[sources.length,'Source files']].map(([count,label])=><div key={String(label)}><strong>{count}</strong><span>{label}</span></div>)}</div><p>IDs, floor relationships and supplied records have been matched. No property forms to fill in.</p><div className="rw-review-summary"><strong>{result?.issues.length??0} geometry findings need review</strong><p>{result?.issues.length?'Open the map to inspect highlighted buildings against their parcel and street boundaries.':'No intersections found by the supported checks. Missing evidence is still unresolved.'}</p></div><details className="rw-other-samples"><summary>What was used · {sources.length-retained} read, {retained} supporting files retained</summary><p>Map geometry comes from the declared vector and schedule sources. Raster, point-cloud and document originals are available for inspection; their receipt is not an extraction or approval result.</p>{sources.map(s=><div className="rw-receipt-file" key={s.id}><span>{s.label}</span><small>{s.processing==='retained'?'Retained original':'Read & matched'}</small></div>)}</details><button className="rw-change-file" onClick={onReset}>Choose another file</button><div className="rw-import-footer"><p>Draft preview · not saved or recorded. Downloading the original package preserves this exact input.</p><button className="rw-primary" onClick={onOpen}>Review on map <ArrowRight size={16}/></button></div></>}
 </div>;
}
