'use client';
import dynamic from 'next/dynamic';
import {assignApplicationIdentifiers,withApplicationIdentifiers,type ApplicationIdentifier} from '../reference-runtime/application-identifiers';
import {useDebouncedValue,useResource} from '../../officer/shared/hooks';
import type {DatasetIdentityMatch} from '@/lib/spatial-datasets';
import {savedDatasetUrl,type SavedSpatialDataset} from '@/lib/spatial-datasets';
import Link from 'next/link';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Search,Upload,Download,ShieldCheck,X,FileText,Layers3,ExternalLink} from 'lucide-react';
import {normalizeReferencePackage} from '../reference-import/browser';
import {deriveSpatialChecks,multiPolygonArea} from '../reference-runtime/spatial-checks';
import type {ReferenceRuntime} from '../reference-runtime/map';
import type {ReferenceScene} from '../layers/ReferenceLayer';
import {useSpatialServices} from '../data/Provider';
import {createSceneRecords,type ReferenceSearchResult} from '../reference-runtime/records';
import {PropertyContext,FloorRegister,RegisterToolbar,type RegisterMode} from './PropertyRegister';
import {ImportReceipt} from './ImportReceipt';
import {demoDataset,demoDatasets,demoDatasetUrl} from './demo-datasets';
import './workbench.css';
import './responsive.css';

const MapViewport=dynamic(()=>import('../MapViewport').then(m=>m.MapViewport),{ssr:false});
type Imported=Awaited<ReturnType<typeof normalizeReferencePackage>>;
type Issue={id:string;title?:string;description?:string;code:string;objectIds?:string[];evidence?:{areaM2?:number;volumeM3?:number}};
const download=(bytes:BlobPart,name:string,type:string)=>{const url=URL.createObjectURL(new Blob([bytes],{type}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
const number=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)?v.toLocaleString('en-IN',{maximumFractionDigits:2}):'Not supplied';

export default function ReferenceWorkbench({datasetId,savedId}:{datasetId?:string;savedId?:string}){
 const {resources}=useSpatialServices();
 const [saved,setSaved]=useState<SavedSpatialDataset|null>(null);
 const saveLock=useRef(false);
 const [imported,setImported]=useState<Imported|null>(null),[pending,setPending]=useState<Imported|null>(null),[dialog,setDialog]=useState<'import'|'sources'|'findings'|'export'|'record'|null>(null),[recordId,setRecordId]=useState<string|null>(null),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [sectionHeight,setSectionHeight]=useState(0),[activeResult,setActiveResult]=useState(0);
 const searchInput=useRef<HTMLInputElement>(null);
 useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();searchInput.current?.focus();}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[]);
 const [view,setView]=useState<'map'|'register'>('map'),[floorId,setFloorId]=useState('all'),[registerMode,setRegisterMode]=useState<RegisterMode>('exploded');
 const runtime=useRef<ReferenceRuntime|null>(null),dialogRef=useRef<HTMLDialogElement>(null),requestId=useRef(0);
 const scene=useMemo(()=>imported?deriveSpatialChecks(imported.render.scene) as ReferenceScene&{issues:Issue[]}:null,[imported]);
 const issues:Issue[]=scene&&Array.isArray(scene.issues)?scene.issues:[];
 const buildings=scene?.objects.filter(o=>o.type==='building')??[];
 const records=useMemo(()=>scene?createSceneRecords(scene):null,[scene]);
 const settledQuery=useDebouncedValue(query.trim());
 const savedSearch=useResource<{matches:DatasetIdentityMatch[]}>(settledQuery?`/spatial-datasets/search?q=${encodeURIComponent(settledQuery)}`:null);
 const results=query.trim()?records?.search(query).slice(0,8)??[]:[];
 const otherResults=settledQuery===query.trim()?(savedSearch.data?.matches??[]).filter(r=>r.datasetId!==(saved?.id??savedId)).slice(0,6):[];
 const chooseIndex=(index:number)=>{if(results[index])choose(results[index]);else if(otherResults[index-results.length])window.location.assign(otherResults[index-results.length].href);};
 const selected=scene?.objects.find(o=>o.id===recordId),selectedGeometry=scene?.geometries.find(g=>g.id===selected?.geometryId) as (ReferenceScene['geometries'][number]&{areaM2?:number})|undefined;
 const setDataset=useCallback((next:Imported)=>{const focal=(next.render.scene.metadata as {focalObjectId?:unknown}).focalObjectId;setView('map');setFloorId('all');setImported(next);setPending(null);setRecordId(typeof focal==='string'&&next.render.scene.objects.some(o=>o.id===focal&&o.type==='building')?focal:next.render.scene.objects.find(o=>o.type==='building')?.id??null);setQuery('');setError('');setNotice('Draft map · original files retained');setSaved(null);resources.replace('reference-active-preview',next);},[resources]);
 useEffect(()=>{
  let active=true;const dataset=demoDataset(datasetId)??demoDatasets[0];
  const key=savedId?`saved-spatial:${savedId}`:`reference-source:${dataset.file}`;
  const cached=!savedId?((datasetId?undefined:resources.read<Imported>('reference-active-preview').data)??resources.read<{value:Imported}>(key).data?.value):null;
  if(cached){setDataset(cached);return;}
  setBusy(true);
  const release=resources.acquire(key,async signal=>{
   let receipt:SavedSpatialDataset|undefined;
   if(savedId){const response=await fetch(`/api/v1/spatial-datasets/${savedId}`,{signal,cache:'no-store'});if(!response.ok)throw new Error('Saved dataset is unavailable. Return to the dataset list and retry.');receipt=await response.json();}
   const response=await fetch(savedId?`/api/v1/spatial-datasets/${savedId}?original=1`:`/reference/${dataset.file}`,{signal,cache:'no-store'});
   if(!response.ok)throw new Error('The source package is unavailable.');
   const value=await normalizeReferencePackage(receipt?.originalName??dataset.file,new Uint8Array(await response.arrayBuffer()));
   if(receipt&&(value.receipt.originalSha256!==receipt.sha256||value.render.scene.canonicalSnapshotDigest!==receipt.digest))throw new Error('Saved dataset fingerprint differs from its stored snapshot.');
   let assignments:ApplicationIdentifier[];
   if(savedId){const response=await fetch(`/api/v1/spatial-datasets/${savedId}?identifiers=1`,{signal,cache:'no-store'});if(!response.ok)throw new Error('Property identifiers could not be loaded.');assignments=await response.json();}
   else assignments=await assignApplicationIdentifiers(value.render.scene,value.receipt.originalSha256);
   value.render.scene=withApplicationIdentifiers(value.render.scene,assignments);
   return {value,receipt};
  });
  const apply=()=>{if(!active||requestId.current!==0)return;const result=resources.read<{value:Imported;receipt?:SavedSpatialDataset}>(key);if(result.data){setDataset(result.data.value);if(result.data.receipt){setSaved(result.data.receipt);setNotice('Saved dataset · originals and spatial records retained');}setBusy(false);}if(result.error){setError(result.error);setBusy(false);}};
  const unsubscribe=resources.subscribe(key,apply);apply();
  return ()=>{active=false;unsubscribe();release();};
 },[resources,setDataset,datasetId,savedId]);
 const saveDataset=async()=>{
  if(!imported||saveLock.current)return;saveLock.current=true;setBusy(true);setError('');
  try{const response=await fetch('/api/v1/spatial-datasets',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-File-Name':encodeURIComponent(imported.receipt.name)},body:new Uint8Array(imported.receipt.originalBytes)});const body=await response.json();if(!response.ok)throw new Error(body.error?.message??'Dataset could not be saved.');setSaved(body);resources.invalidate(key=>key==='/spatial-datasets'||key.startsWith('/spatial-datasets/search')||key.startsWith('/work-queue'));window.history.replaceState(null,'',savedDatasetUrl(body.id));setNotice('Dataset saved · original files and spatial records retained');}
  catch(e){setError(e instanceof Error?e.message:'Save failed.');setNotice('Save failed. Your current draft is still open.');}finally{saveLock.current=false;setBusy(false);}
 };
 useEffect(()=>{const node=dialogRef.current;if(dialog&&!node?.open)node?.showModal();else if(!dialog&&node?.open)node.close();},[dialog]);
 const selectionChanged=useCallback((id:string)=>{setRecordId(id);const current=runtime.current?.getState() as {sectionHeight?:number}|undefined;if(typeof current?.sectionHeight==='number')setSectionHeight(current.sectionHeight);},[]);
 const inspect=useCallback((id:string)=>{runtime.current?.select(id,false,false);selectionChanged(id);setFloorId('all');setView('register');},[selectionChanged]);
 const ready=useCallback((v:ReferenceRuntime)=>{runtime.current=v;v.setPresentation?.(view==='register'?registerMode:'block');const saved=v.getState() as {selectedId?:string;floor?:string};if(saved.selectedId)setRecordId(saved.selectedId);setFloorId(saved.floor??'all');const current=v.getState() as {sectionHeight?:number};if(typeof current.sectionHeight==='number')setSectionHeight(current.sectionHeight);const params=new URLSearchParams(window.location.search),building=params.get('building'),floor=params.get('floor');if(building){v.select(building);setRecordId(building);if(floor){v.setFloor?.(floor);setFloorId(floor);}}},[view,registerMode]);
 useEffect(()=>{const viewer=runtime.current;if(!viewer)return;viewer.setPresentation?.(view==='register'?registerMode:'block');const saved=viewer.getState() as {selectedId?:string;floor?:string};if(saved.selectedId)setRecordId(saved.selectedId);setFloorId(saved.floor??'all');const current=viewer.getState() as {sectionHeight?:number};if(typeof current.sectionHeight==='number')setSectionHeight(current.sectionHeight);},[view,registerMode]);
 const chooseFloor=useCallback((id:string)=>{setFloorId(id);runtime.current?.setFloor?.(id);},[]);
 const ingest=async(load:()=>Promise<File>)=>{
  const id=++requestId.current;setBusy(true);setError('');setPending(null);
  try{const upload=await load();if(requestId.current!==id)return;const result=await normalizeReferencePackage(upload.name,new Uint8Array(await upload.arrayBuffer()));result.render.scene=withApplicationIdentifiers(result.render.scene,await assignApplicationIdentifiers(result.render.scene,result.receipt.originalSha256));if(requestId.current===id)setPending(result);}
  catch(e){if(requestId.current===id){const issues=e&&typeof e==='object'&&'issues' in e&&Array.isArray(e.issues)?e.issues:[];setError(issues.length?'This file does not match a supported scene format. Use a source package or normalized JSON with metadata, coordinates and source records. Your current map is unchanged.':e instanceof Error?e.message:'Unable to read the package.');}}
  finally{if(requestId.current===id)setBusy(false);}
 };
 const choose=(result:ReferenceSearchResult)=>{runtime.current?.select(result.buildingId);setRecordId(result.buildingId);if(result.floorId)chooseFloor(result.floorId);else{setFloorId('all');const viewer=runtime.current;if(viewer)viewer.restoreState({...viewer.getState() as Record<string,unknown>,floor:'all',inspectorTab:'overview'});}setQuery('');};
 useEffect(()=>{if(new URLSearchParams(window.location.search).get('import')==='1')setDialog('import');},[]);
 const sourceCount=scene?.sources.length??0;
 const section=selectedGeometry&&typeof selectedGeometry.baseElevationM==='number'&&typeof selectedGeometry.heightM==='number'&&selectedGeometry.heightM>0?{min:selectedGeometry.baseElevationM,max:selectedGeometry.baseElevationM+selectedGeometry.heightM,value:sectionHeight,onChange:(height:number)=>{setSectionHeight(height);const viewer=runtime.current;if(viewer)viewer.restoreState({...viewer.getState() as Record<string,unknown>,sectionHeight:height});}}:null;
 const downloadSource=(id:string)=>{const source=scene?.sources.find(s=>s.id===id);const path=typeof source?.originalUri==='string'?source.originalUri.replace(/^dataset\//,''):'';const bytes=imported?.receipt.files.get(path)??[...(imported?.receipt.files??[])].find(([name])=>name.endsWith('/'+path))?.[1];if(bytes)download(new Uint8Array(bytes),path.split('/').at(-1)??'source',source?.mimeType??'application/octet-stream');else setNotice('The original is not available as a separate file in this receipt. Download the original package.');};
 const registerProps=scene&&recordId?{scene,buildingId:recordId,floorId,mode:registerMode,onFloor:chooseFloor,onMode:setRegisterMode,onBack:()=>setView('map'),onSources:()=>setDialog('sources'),onSource:downloadSource}:null;
 return <div className="reference-workbench">
  <a href="#reference-map" className="rw-skip">Skip to map</a>
  <header className="rw-header">
   <Link href="/studio/work" className="rw-brand"><strong>3D ULPIN</strong><small>Property mapping</small></Link>
   <nav className="rw-nav" aria-label="Product sections"><Link href="/studio/work">Batches</Link><Link aria-current={view==='map'?'page':undefined} href="/studio/datasets">Map</Link><Link aria-current={view==='register'?'page':undefined} href="/studio/registry">Register</Link></nav>
   <div className="rw-search"><Search size={17}/><input ref={searchInput} role="combobox" aria-autocomplete="list" aria-expanded={!!query.trim()} aria-controls="rw-search-options" aria-activedescendant={query.trim()&&(results.length+otherResults.length)?`rw-result-${Math.min(activeResult,results.length+otherResults.length-1)}`:undefined} aria-label="Search properties by ULPIN" placeholder="Search 2D ULPIN / 3D ULPIN / floor" value={query} onChange={e=>{setQuery(e.target.value);setActiveResult(0);}} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setActiveResult(v=>Math.min(v+1,results.length+otherResults.length-1));}if(e.key==='ArrowUp'){e.preventDefault();setActiveResult(v=>Math.max(0,v-1));}if(e.key==='Enter')chooseIndex(Math.max(0,activeResult));if(e.key==='Escape')setQuery('');}}/><kbd>⌘ K</kbd>{query&&<div className="rw-search-results" id="rw-search-options" role="listbox" aria-label="Matching properties">{results.map((o,index)=><button id={`rw-result-${index}`} role="option" aria-selected={index===activeResult} key={o.objectId} onClick={()=>choose(o)}><span><strong>{o.identifier}</strong><small>{o.label}</small></span><span>{o.matchedBy}</span></button>)}{otherResults.map((r,index)=><button id={`rw-result-${results.length+index}`} role="option" aria-selected={activeResult===results.length+index} key={`${r.datasetId}:${r.objectId}`} onClick={()=>window.location.assign(r.href)}><span><strong>{r.identifier}</strong><small>{r.datasetName} · {r.label}</small></span><span>Open map →</span></button>)}{savedSearch.loading&&<p>Searching saved datasets…</p>}{savedSearch.error&&<p role="alert">Saved search unavailable. <button onClick={()=>void savedSearch.reload()}>Retry</button></p>}{!results.length&&!otherResults.length&&!savedSearch.loading&&<p>No matching property.</p>}</div>}</div>
   <div className="rw-actions">{saved&&<Link href={`/studio/processing/${saved.id}`}>Prepare with ML</Link>}{imported&&!saved&&<button disabled={busy} onClick={()=>void saveDataset()}>{busy?'Saving…':'Save dataset'}</button>}<button className="rw-import-action" disabled={busy} onClick={()=>setDialog('import')}><Upload size={15}/>Import</button><button onClick={()=>setDialog('export')} disabled={!imported} aria-label="Download dataset"><Download size={17}/></button></div>
  </header>
  <div className="rw-context"><strong>{scene?.metadata.title.split(' · ')[0]??'Choose a dataset'}</strong><span className="rw-preview-tag">{saved?'Saved':'Unsaved preview'}</span><button onClick={()=>setDialog('sources')}>{sourceCount} source files</button><button className="rw-review-action" onClick={()=>setDialog('findings')} disabled={!scene}><ShieldCheck size={13}/>{issues.length?`${issues.length} findings to review`:'Review checks'}</button></div>
  {error&&scene&&<p className="rw-error" role="alert">{error}</p>}
  <main id="reference-map" className={`rw-map ${view==='register'?'rw-register':''}`}>{view==='register'&&registerProps&&<PropertyContext {...registerProps}/>}<div className="rw-viewport">{view==='register'&&registerProps&&<RegisterToolbar {...registerProps} section={section}/>}<div className="rw-view-canvas">{scene?<MapViewport source={{kind:'canonical-scene',props:{scene,sessionKey:`reference:${scene.canonicalSnapshotDigest}`,onSelect:selectionChanged,onFloorSelect:setFloorId,onRegister:inspect,onReview:()=>setDialog('findings'),onReady:ready}}}/>:<div className="rw-loading"><Layers3 size={32}/><h1>{busy?'Preparing the neighbourhood…':'Open a neighbourhood'}</h1><p>{error||'Verifying source bytes, identities and geometry.'}</p><button onClick={()=>setDialog('import')}>Import a source package</button></div>}</div></div>{view==='register'&&registerProps&&<FloorRegister {...registerProps}/>}</main>
  <div className="rw-status" role="status">{notice||'Local source preview'}<button onClick={()=>setDialog('sources')}>Source receipt <ExternalLink size={11}/></button></div>
  <dialog ref={dialogRef} className="rw-dialog" onCancel={()=>setDialog(null)} onClose={()=>setDialog(null)}>
   <div className="rw-dialog-heading"><div><small>3D ULPIN / {dialog==='record'?'PROPERTY RECORD':'DATA TOOLS'}</small><h2>{dialog==='import'?'Import a neighbourhood':dialog==='sources'?'Source files':dialog==='findings'?'Spatial findings':dialog==='export'?'Export this dataset':selected?.label??'Property record'}</h2></div><button aria-label="Close dialog" onClick={()=>setDialog(null)}><X size={20}/></button></div>
   {dialog==='import'&&<ImportReceipt onReset={()=>{setPending(null);setError('');}} pending={pending} busy={busy} error={error} onDownload={()=>{void (async()=>{try{const response=await fetch('/reference/lake-view-complete.zip');if(!response.ok)throw new Error('The sample package is unavailable.');download(new Uint8Array(await response.arrayBuffer()),'lake-view-complete.zip','application/zip');}catch(e){setError(e instanceof Error?e.message:'Download failed. Try again.');}})();}} onFile={upload=>void ingest(async()=>upload)} onSample={path=>void ingest(async()=>{const response=await fetch(`/reference/${path}`);if(!response.ok)throw new Error('The sample file is unavailable.');return new File([await response.arrayBuffer()],path);})} onOpen={()=>{if(pending){const bundled=demoDatasets.find(d=>d.file===pending.receipt.name);window.history.replaceState(null,'',bundled?demoDatasetUrl(bundled.id):'/studio/showcase');setDataset(pending);setDialog(null);}}}/>}
   {dialog==='sources'&&imported&&<><p><strong>{scene?.metadata.title}</strong></p><p>Original package → canonical records → assigned identifiers → shared map. This dataset contains synthetic demonstration records; it is not a surveyed ownership record.</p><p>3D IDs are application assignments linked to the saved source and object. Floor suffixes use explicit source levels. They are not government-issued ULPINs. A 2D ULPIN is displayed only when a 14-character value was supplied; legacy demo references remain in the originals and search history.</p><details className="rw-technical"><summary>Technical receipt & fingerprints</summary><dl className="rw-fields"><dt>Input contract</dt><dd>{imported.canonical.source.schemaVersion}</dd>{imported.receipt.extraction&&<><dt>Extraction</dt><dd>{imported.receipt.extraction.sourceFiles} original source files → normalized records</dd></>}<dt>Canonical contract</dt><dd>{imported.canonical.input.schemaVersion}</dd><dt>Original SHA-256</dt><dd><code>{imported.receipt.originalSha256}</code></dd><dt>Snapshot digest</dt><dd><code>{scene?.canonicalSnapshotDigest}</code></dd><dt>Frame</dt><dd>{scene?.frames[0]?.name}</dd><dt>Vertical reference</dt><dd>{scene?.frames[0]?.verticalDatum}</dd></dl></details>{scene?.sources.map(s=><article className="rw-source" key={s.id}><FileText size={18}/><div><strong>{s.label}</strong><span>{s.mimeType} · revision {s.revision}</span></div><button className="rw-source-download" onClick={()=>downloadSource(s.id)} aria-label={`Download ${s.label}`}><Download size={16}/></button></article>)}{scene?.survey.assets.length? <><h3>Rendered survey sources</h3><p>Switch Map tools → Layers → Map data to inspect the original point cloud, imagery or elevation grid. The building model is supplied separately; displaying a source is not building extraction.</p>{scene.survey.assets.map(a=><p className="rw-note" key={a.id}>{a.label} · {a.sourcePath} · {a.kind==='lidar'?`${a.pointCount?.toLocaleString('en-IN')} points`:`${a.sourceWidth} × ${a.sourceHeight} pixels`} · {a.classification}</p>)}</>:null}{scene?.survey.diagnostics.map((d,i)=><p className="rw-note" key={`survey-${i}`}>{d.path}: {d.message}</p>)}<h3>Import limitations</h3>{imported.canonical.diagnostics.filter(d=>d.severity==='unsupported').map((d,i)=><p className="rw-note" key={i}>{d.objectId}: {d.message}</p>)}<p className="rw-note">Utility XYZ alignments can be displayed along their original segments; analytical clearance remains unavailable in this profile.</p></>}
   {dialog==='findings'&&<><p>Positive-area intersections computed from the loaded geometry. Shared walls are excluded. These are geometry findings for review.</p>{issues.map(i=><article className="rw-finding" key={i.id}><strong>{i.title??i.code}</strong><span>{number(i.evidence?.areaM2)} m²</span><p>{i.description}</p>{i.objectIds?.filter(id=>buildings.some(b=>b.id===id)).map(id=><button key={id} onClick={()=>{runtime.current?.select(id);setDialog(null);}}>Inspect {scene?.objects.find(o=>o.id===id)?.label??id} →</button>)}</article>)}{!issues.length&&<p>No findings in the qualified comparisons. Missing geometry is not a clearance result.</p>}</>}
   {dialog==='export'&&imported&&<><p>Export the original receipt or the canonical candidate with its source bindings.</p><button className="rw-export" onClick={()=>download(new Uint8Array(imported.receipt.originalBytes),imported.receipt.name,imported.receipt.name.endsWith('.zip')?'application/zip':'application/json')}><Download size={19}/><span><strong>Original source package</strong><small>Byte-identical to the imported file</small></span></button><button className="rw-export" onClick={()=>download(JSON.stringify({input:imported.canonical.input,manifest:imported.canonical.snapshot.manifest,diagnostics:imported.canonical.diagnostics,presentation:imported.presentation},null,2),'canonical-candidate.json','application/json')}><Download size={19}/><span><strong>Canonical candidate & receipt</strong><small>Versioned identities, geometry and provenance</small></span></button><p className="rw-note">The canonical export is an inspection artifact. Reimport the original package through this compatibility profile.</p></>}
   {dialog==='record'&&selected&&<><p className="rw-note">{selected.id} · internal identity {selected.systemId??'Not supplied'} · official ULPIN not issued</p><dl className="rw-fields"><dt>Geometry</dt><dd>{selectedGeometry?.type??'Unavailable'}</dd><dt>Footprint</dt><dd>{number(selectedGeometry?.type==='Polygon'?multiPolygonArea([selectedGeometry.coordinates]):selectedGeometry?.type==='MultiPolygon'?multiPolygonArea(selectedGeometry.coordinates):null)} m²</dd><dt>Height</dt><dd>{selectedGeometry?.heightM==null?'Unknown':`${number(selectedGeometry.heightM)} m`}</dd><dt>Source revision</dt><dd>{selectedGeometry?.version??'Unavailable'}</dd></dl><h3>Floors & spaces</h3>{scene?.objects.filter(o=>scene.relations.some(r=>r.fromId===selected.id&&r.toId===o.id&&r.kind==='contains')).map(o=><button className="rw-record-row" key={o.id} onClick={()=>{runtime.current?.setFloor?.(o.id);setDialog(null);}}><Layers3 size={16}/><strong>{o.label}</strong><span>{o.id}</span></button>)}<h3>Source records</h3>{selected.sourceRecordIds.map(id=>{const source=scene?.sourceRecords.find(s=>s.id===id);return <article className="rw-source" key={id}><FileText size={16}/><div><strong>{source?.sourceId??id}</strong><span>{source?.locator??'Unavailable'}</span></div></article>;})}<p className="rw-note">Ownership, approvals and plan boundaries are not inferred from the exterior model. Use Property Register to explore supplied floors and resident schedules.</p></>}
  </dialog>
 </div>;
}
