import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { pool, transaction } from "../apps/web/lib/server/db";
import type {
  CaseDetail,
  RegistryDraft,
  RegistryReview,
  RegistrySite,
} from "../packages/contracts/src";
const api = async <T>(path: string, body?: unknown): Promise<T> => {
  const response = await fetch(`http://127.0.0.1:3000/api/v1${path}`, {
    method: body ? "POST" : "GET",
    headers: body ? { "Content-Type": "application/json" } : undefined,
    body: body ? JSON.stringify(body) : undefined,
  });
  const value = await response.json();
  assert(response.ok, JSON.stringify(value));
  return value;
};
const report = JSON.parse(
  await readFile("test-results/demo-verification.json", "utf8"),
);
const caseId = report.evidence.find(
  (r: { dataset: string }) => r.dataset === "c001",
).caseId;
const c = await api<CaseDetail>(`/cases/${caseId}`);
assert(
  c.case.name === "Verification — C001" &&
    c.case.description.includes("repeatable input-to-model verification"),
  "Only a case generated by test:demo may be used.",
);
const site = await api<RegistrySite>("/sites", {
  name: `ZZ import verification ${randomUUID()}`,
  frame: c.case.frame,
  synthetic: true,
});
try {
  const imported = await api<{ draftId: string }>(`/sites/${site.id}/import`, {
    caseId,
    expectedRevision: c.case.revision,
  });
  const draft = await api<RegistryDraft>(
    `/registry-drafts/${imported.draftId}`,
  );
  for (const r of draft.records.filter((r) => r.kind === "space")) {
    const original = c.model!.units.find((u) => u.alias === r.alias)!;
    assert.equal(
      r.rights.length,
      0,
      "Importing geometry must not invent rights.",
    );
    for (const binding of Object.values(original.bindings))
      assert(
        r.evidence.some(
          (e) =>
            e.sourceId === binding!.sourceId && e.locator === binding!.locator,
        ),
      );
  }
  const review = await api<RegistryReview>(
    `/registry-drafts/${draft.id}/review`,
    { expectedRevision: draft.revision, expectedSiteRevision: 0 },
  );
  assert(!review.findings.some((f) => f.severity === "error"));
  console.log(
    "PASS Real inspected/build case imports as a reviewable draft with original bound evidence and no invented rights.",
  );
} finally {
  await transaction(async (client) => {
    const published = await client.query(
      "SELECT id FROM registry_records WHERE site_id=$1 AND revision>0",
      [site.id],
    );
    assert.equal(
      published.rowCount,
      0,
      "Never remove published records during verification cleanup.",
    );
    await client.query(
      "DELETE FROM registry_reviews WHERE draft_id IN (SELECT id FROM registry_drafts WHERE site_id=$1)",
      [site.id],
    );
    await client.query("DELETE FROM registry_aliases WHERE site_id=$1", [
      site.id,
    ]);
    await client.query("DELETE FROM registry_drafts WHERE site_id=$1", [
      site.id,
    ]);
    await client.query(
      "DELETE FROM registry_records WHERE site_id=$1 AND revision=0",
      [site.id],
    );
    await client.query(
      "UPDATE cases SET site_id=NULL,archived=true WHERE id=$1 AND site_id=$2",
      [caseId, site.id],
    );
    await client.query(
      "DELETE FROM registry_sites WHERE id=$1 AND revision=0",
      [site.id],
    );
  });
  await pool().end();
}
