export const steps = [
  { label: 'Source', kicker: '01 / RETAIN THE ORIGINAL', title: 'Every record starts with evidence.', body: 'A floor plan arrives as an image or PDF page. The system retains the original bytes and a fingerprint, then prepares an upright image for local inference.', input: 'Image or selected PDF page', output: 'Retained source + inference raster', owner: 'Application + private storage', note: 'We start from a real source document. Nothing the model does replaces that original.', limit: 'This example uses published CubiCasa5K test plan 1191. It is not a survey of the demonstration property.' },
  { label: 'Extract', kicker: '02 / LOCAL MACHINE LEARNING', title: 'Pixels become proposed regions.', body: 'CubiCasa5K predicts room and wall classes. The processor traces those pixels into polygons. For aerial imagery, RF-DETR proposes building regions instead.', input: 'Pixels on the retained image grid', output: 'Candidate polygons + model scores', owner: 'ONNX Runtime · CPU inference', note: 'The model gives the officer a starting point. Toggle the overlay to see both the useful predictions and the mistakes.', limit: 'These are actual retained predictions. Some regions merge adjacent spaces; model scores are not survey accuracy.' },
  { label: 'Calibrate', kicker: '03 / PIXELS TO METRES', title: 'A prediction needs a real scale.', body: 'Two documented control pairs establish scale, rotation and translation in a named metre frame. The selected contour is then sent to fact review.', input: 'Selected contour + control evidence', output: 'Unreviewed metric geometry', owner: 'Officer review + application transform', note: 'AI sees pixels. Documented control points tell us where those pixels belong and how large they are.', limit: 'The retained test uses synthetic controls: 768 pixels span 40 metres. Two controls cannot correct perspective or uneven scan distortion.' },
  { label: 'Build', kicker: '04 / GEOMETRY PROCESSING', title: 'Give the reviewed outline height.', body: 'Separately supported lower and upper levels define the vertical extent. The geometry worker calculates a prism from the reviewed footprint and computes area, volume and supported intersections.', input: 'Reviewed outline + lower/upper levels', output: 'Proposed 3D geometry + findings', owner: 'Python geometry worker · Shapely', note: 'The third dimension comes from evidence. The area and volume are geometry calculations, not numbers guessed by AI.', limit: 'This test uses an authored 3 m height. The view is a schematic projection of the retained contour; it does not establish correct room semantics.' },
  { label: 'Record', kicker: '05 / REVIEW & RECORD', title: 'A 3D result with a paper trail.', body: 'After explicit review, the application records a technical revision linked to source evidence, geometry and processing fingerprints. Earlier revisions and original files remain available.', input: 'Checked proposal + review decision', output: 'Evidence-linked technical revision', owner: 'Application + PostgreSQL / PostGIS', note: 'We can explain where the shape came from, which model proposed it and what evidence supplied its scale and height.', limit: 'This is a retained synthetic verification record, not a newly saved record or an official identity or ownership decision.' },
] as const;

export const systems = [
  {id:'studio',title:'Studio',sub:'Next.js · React · shared viewport',lane:0,x:3,y:34,icon:'screen',description:'The officer uploads evidence, inspects predictions and reviews proposed records. The shared viewport displays canonical geometry; camera and floor-separation changes affect presentation only.',input:'Operator actions + saved data',output:'Explicit requests to the application',note:'A model suggestion never records itself.'},
  {id:'api',title:'Application API',sub:'Next.js · revision guards',lane:1,x:29,y:13,icon:'server',description:'Owns source receipts, evidence bindings, calibration, review and recording. Rejects stale inputs and conflicting replays. All application database writes belong to this boundary.',input:'Sources, reviewed controls and decisions',output:'Durable jobs, proposals and revisions',note:'The application is the authority for workflow state.'},
  {id:'db',title:'Record store',sub:'PostgreSQL / PostGIS',lane:1,x:29,y:43,icon:'database',description:'Retains case state, source associations, stable identities, geometry revisions, job records and history. A new technical revision does not overwrite earlier evidence.',input:'Validated application transactions',output:'Saved records + revision history',note:'The Python worker has no application database access.'},
  {id:'dispatcher',title:'Job dispatcher',sub:'Submit · poll · validate',lane:1,x:29,y:73,icon:'route',description:'Reads durable application jobs, submits them to the private processor, polls completion, checks output contracts and fingerprints, and ingests results transactionally.',input:'Durable jobs + private job results',output:'Processing requests + retained results',note:'Late or stale output cannot silently replace current work.'},
  {id:'storage',title:'Originals & artifacts',sub:'Private S3 / MinIO',lane:2,x:72,y:13,icon:'files',description:'Stores original bytes and retained inference rasters and masks. Fingerprints identify the exact evidence used. The worker verifies source size and hash before processing.',input:'Original source and derived artifact bytes',output:'Verified bytes for inference and review',note:'Original evidence survives model errors and retries.'},
  {id:'queue',title:'Private job service',sub:'FastAPI → Redis → Celery',lane:2,x:72,y:43,icon:'layers',description:'Accepts private processing requests and dispatches independent background jobs. Each source can retain successful, empty, failed or retried attempts without replacing successful siblings.',input:'Fingerprint-bound job requests',output:'Worker tasks + job status',note:'The UI can close while the processing continues.'},
  {id:'worker',title:'ML & geometry worker',sub:'ONNX Runtime · Rasterio · Shapely',lane:2,x:72,y:73,icon:'cpu',description:'Runs the pinned local models, traces predicted pixels into polygons and, in separate geometry operations, computes reviewed prisms and intersections. It returns results through the private job service.',input:'Verified sources + processing profile',output:'Masks, contours, receipts or geometry',note:'Inference proposes; geometry computes; the officer reviews.'},
] as const;

export type SystemId = typeof systems[number]['id'];
